### ISSUE TITLE
Scenarios are not running: EndpointPlaintext, MvcPlaintext, Plaintext, PlaintextNonPipelined, PlaintextPlatform ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#1019]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| EndpointPlaintext | Linux, ARM64, http, KestrelSockets | 5/24/19 9:48:49 AM +00:00 |
| MvcPlaintext | Linux, ARM64, http, KestrelSockets | 5/24/19 9:45:40 AM +00:00 |
| Plaintext | Linux, ARM64, http, KestrelSockets | 5/24/19 9:41:24 AM +00:00 |
| PlaintextNonPipelined | Linux, ARM64, http, KestrelSockets | 5/24/19 9:42:28 AM +00:00 |
| PlaintextPlatform | Linux, ARM64, http, KestrelSockets | 5/24/19 9:38:03 AM +00:00 |
| StaticFiles | Linux, ARM64, http, KestrelSockets | 5/24/19 9:52:01 AM +00:00 |

**Comment by rynowak** [comment]
@sebastienros are your scenarios running?
