### ISSUE TITLE
Core RC1 vs RC2 Performance

### ISSUE THREAD

**Issue by cindro** [aspnet/benchmarks#102]
The benchmark says ASP.NET Core on Kestrel perfsvr = 1,174,881...is this RC2 speed?
If so how fast would RC1 run in the same scenario or did I miss something?

**Comment by mikeharder** [comment]
Here are the approximate values for RC1, RC2, and current:

Build | Plaintext RPS
------------ | -------------
RC1 | 743,000
RC2 | 1,060,000
Current | 1,174,881

**Comment by cindro** [comment]
Thank you @mikeharder, that is very clear.
