### ISSUE TITLE
Performance regression: PlaintextPlatform, PlaintextPlatform

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#1053]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| PlaintextPlatform | Linux, http, KestrelSockets | 2019-06-01 12:01:41Z | 6573567 | 5915256 | -10.01 % | -42.84 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview6-19279-08__
Microsoft.NetCore.App __3.0.0-preview6-27730-01__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview6-19279-08__
Microsoft.NetCore.App __3.0.0-preview7-27731-04__

Commits:

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/e23119d577e644d2c2a25419c88c1181681358e0...0d09364875814e037304dc783516600498ca553b

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/41832cedbb2d46362239d2b272964a39ca37cd89...b8d5b7b760f64d39e00554189ea0e5c66ed6bd62

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| PlaintextPlatform | Windows, http, KestrelSockets | 2019-06-01 12:50:03Z | 6470269 | 5866369 | -9.33 % | -39.17 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview6-19279-08__
Microsoft.NetCore.App __3.0.0-preview6-27730-01__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview6-19279-08__
Microsoft.NetCore.App __3.0.0-preview7-27731-04__

Commits:

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/e23119d577e644d2c2a25419c88c1181681358e0...0d09364875814e037304dc783516600498ca553b

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/41832cedbb2d46362239d2b272964a39ca37cd89...b8d5b7b760f64d39e00554189ea0e5c66ed6bd62

**Comment by benaadams** [comment]
Can't see anything interesting in those diffs, but it affects Windows and Linux equally and is a pretty major regression:

![image](https://user-images.githubusercontent.com/1142958/59040278-46f8c780-886e-11e9-8c6d-d32f1c835132.png)

**Comment by sebastienros** [comment]
It a networking issue probably. Before and after the change we tried to upgrade the NICs but we had to revert them. Trying old version give us the same new results.

**Comment by benaadams** [comment]
> It a networking issue probably. Before and after the change we tried to upgrade the NICs but we had to revert them.

Was that the earlier regression or the current one?

![image](https://user-images.githubusercontent.com/1142958/59058616-f3e63b00-8894-11e9-90b2-e244f5e6987d.png)

**Comment by sebastienros** [comment]
Both. The first one is when we changed the switch configuration so our work machines can submit benchmarks to citrine. The second one is when we tried to setup better NICs.
