### ISSUE TITLE
Add golang results to readme

### ISSUE THREAD

**Issue by valyala** [aspnet/Benchmarks#106]
It would be great to see golang results from TechEmpower benchmarks on the README.md for the following tests:
- [go-std](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Go/go-std)
- [fasthttp](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Go/fasthttp)

**Comment by jadbox** [comment]
This would be great!
