### ISSUE TITLE
Add full .NET Framework

### ISSUE THREAD

**Issue by mikeharder** [aspnet/benchmarks#111]
- [x] Add parameter to Driver, Server, and ServerJob to specify .NET Framework or .NET Core
- [x] Update Server to run Benchmarks on .NET Framework or .NET Core based on parameter
- [x] Add column to SQL
- [x] Add rows to makefile.shade for the following scenarios on .NET Framework
  - Plaintext
  - Plaintext with HTTPS
  - JSON
  - JSON with HTTPS
  - MvcPlaintext
  - MvcJSON
- [x] Update PowerBI report to compare .NET Framework and .NET Core

**Comment by runxc1** [comment]
Is this being worked on or is there any visibility here?   I would love to see the difference between performance of .Net Core and the Full Framework using Asp.Net Core.  Would help with some internal planning.
