### ISSUE TITLE
Add WebListener

### ISSUE THREAD

**Issue by mikeharder** [aspnet/benchmarks#112]
- [x] Add parameter to Driver and ServerJob to specify WebListener or Kestrel
- [x] Update Server to run Benchmarks on WebListener or Kestrel based on parameter
- [x] Add column to SQL
- [x] Add rows to makefile.shade for the following scenarios on WebListener
  - Plaintext
  - Plaintext with HTTPS
  - JSON
  - JSON with HTTPS
- [ ] Update PowerBI report to compare WebListener and Kestrel

Should be similar to the changes required for adding HTTPS: https://github.com/aspnet/benchmarks/commit/f69541f1db186083bab21285ccad2c9cd9f33000

**Comment by Shravan2x** [comment]
This would be nice to have to compare with Kestrel, now that .NET Core 1.1 is out.

**Comment by dougbu** [comment]
@mikeharder is this work a prerequisite for #165?

**Comment by mikeharder** [comment]
It's a dup.  I would close #165 and keep this open since it has more details.

**Comment by dougbu** [comment]
:ok: self-assigning and doing the needful to #165.

**Comment by dougbu** [comment]
f7b0c33

**Comment by dougbu** [comment]
@mikeharder actually not quite done: Need to do a few runs and then update the Power BI configuration.

**Comment by mikeharder** [comment]
Data has been collected and Power BI has been updated.
