### ISSUE TITLE
Measure HTTPS with short-lived connections

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Benchmarks#115]
Our current tests for HTTPS use long-lived connections, which measures the SSL overhead per request on an existing connection, but doesn't measure the cost of new connections (e.g. SSL handshake).  We should add tests for HTTPS with short-lived connections, with a small number of requests (or even a single request) per connection.

This might be possible in wrk by calling `wrk.thread:stop()` (https://github.com/wg/wrk/issues/51), or we might need to use a different benchmark client.

**Comment by tmds** [comment]
@mikeharder is there some benchmark measuring https perf on Linux?

**Comment by mikeharder** [comment]
@tmds: Our existing Benchmarks app can be run on Linux with https:

https://github.com/aspnet/benchmarks/blob/dev/src/Benchmarks/Program.cs#L209-L212

For long-lived connections you can use a client like `wrk`.  We haven't tested short-lived connections yet, so I can't recommend a test client for this.  Client port exhaustion often makes it difficult to benchmark short-lived connections.
