### ISSUE TITLE
Reduce variance of RPS measurements

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Benchmarks#116]
Currently, there's up to 10% variance when measuring RPS, which makes it difficult to determine the accurate impact of a change.  We should investigate, understand, and eliminate the source of this variance.

Also test the variance in throughput when the server is lightly loaded, to determine if it's an artifact of running near capacity, or always the case.

**Comment by roji** [comment]
Yes, I've been running into this as well and it makes it difficult to accurately measure the value of new proposed optimizations... Also related to outputting the standard deviation (#369).
