### ISSUE TITLE
[Question] Is it possible to install libgdiplus on the Linux machines?

### ISSUE THREAD

**Issue by adamsitnik** [aspnet/Benchmarks#1171]
As described in #1170 I am working on making it possible to run the performance repo microbenchmarks using the ASP.NET Infrastructure.

The only blocker that remains active when following PRs get merged:

https://github.com/dotnet/performance/pull/591 (already merged)
https://github.com/dotnet/performance/pull/592 (already merged)
https://github.com/dotnet/performance/pull/594 (already merged)
https://github.com/aspnet/Benchmarks/pull/1170

is missing `libgdiplus` which is used by `System.Drawing` microbenchmarks on Linux.

![obraz](https://user-images.githubusercontent.com/6011991/60355489-cccfe480-99ce-11e9-87be-e6a2971aecde.png)

@sebastienros would it be possible to install `libgdiplus` on the Linux machines in ASP.NET perf lab? Would it be enough if I just send a PR to

https://github.com/aspnet/Benchmarks/blob/06f077bdb6a47bcf24d926d8e40208d76724c7f2/docker/benchmarks/Dockerfile#L3-L6

and extend it with `libgdiplus` ?

**Comment by sebastienros** [comment]
As long as this compatible with the base docker image, it's totally fine.
