### ISSUE TITLE
Scenarios are not running: GrpcUnaryNative

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#1189]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| GrpcUnaryNative | Windows, Physical, http, KestrelSockets | 7/12/19 6:15:41 PM +00:00 |

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
Looks like it is still running to me:

![image](https://user-images.githubusercontent.com/303201/61344530-af8f8700-a8a5-11e9-9907-54ff2380701e.png)
