### ISSUE TITLE
improve how the ef dbcontext is setup

### ISSUE THREAD

**Issue by nathana1** [aspnet/benchmarks#120]
From the comments in https://github.com/aspnet/benchmarks/pull/107:

This is an unusual way to do service replacement. I'm guessing this is because you don't want EF to share the same service provider as the application and you don't want to manage the service provider yourself?
The more normal way to do this would be to change AddDbContext as follows:
services
    .AddScoped<ISqlServerConnection, NoTransactionSqlServerConnection>()
    .AddEntityFrameworkSqlServer()
    .AddDbContext<ApplicationDbContext>(
        (serviceProvider, options) => options
            .UseInternalServiceProvider(serviceProvider)
            .UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
That being said, if you want to do it this way, then its probably fine.

**Comment by divega** [comment]
You can probably also use the new flag to opt out of wrapping SaveChanges() in transactions which was added for EF Core 1.1 instead of the service replacement approach currently used:

context.Database.AutoTransactionsEnabled = false;
