### ISSUE TITLE
Use Maestro APIs to find what version of ASP.NET Core and .NET Core to use

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Benchmarks#1210]
Today were hitting the nuget feed directly and pulling .NET Core 5 builds. Instead, we should be using the .NET Core 3.0 channel and pulling the appropriate builds from that.

**Comment by anurse** [comment]
Yep, we should use Maestro "channels". There's a simple REST API that can be used to query for the most recent build of a repo associated with a specific channel. That data is kept up-to-date as branches change around, so we can reliably get the latest ".NET Core 3.0" builds even when corefx changes branches around, etc.

I've got context on the specific APIs to help get this up and running.

**Comment by davidfowl** [comment]
I hacked some stuff together last night from what you showed me.
