### ISSUE TITLE
Add support for non-MSSQL database providers

### ISSUE THREAD

**Issue by roji** [aspnet/benchmarks#122]
The data benchmarks are currently hardcoded to use MSSQL, but it should be possible to test with other providers (e.g. Npgsql) based on configuration. This involves at least the following aspects:

* Plugging in a different DbProviderFactory (ADO.NET level)
* Plugging in a different EFCore provider
* Different SQL queries for raw mode (e.g. `SELECT [Id], [Message] FROM [Fortune]` becomes `SELECT ""Id"", ""Message"" FROM ""Fortune""` in Npgsql.

**Comment by nathana1** [comment]
We have this working for PostgreSQL, you can just change appsettings.json to something like:

{
  "ConnectionString": "...",
  "Database": "postgresql"
}

And it should work.  Let us know if you if there is anything else you'd like to see.

**Comment by roji** [comment]
It's really great to see this @nathana1, I hope I'll have some time soon to test things on my own and optimize Npgsql further where needed.
