### ISSUE TITLE
Performance regression: MemoryCachePlaintext

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#1309]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MemoryCachePlaintext | Windows, http, KestrelSockets | 2019-08-13 19:44:22Z | 4417916 | 4284896 | -3.01 % | -2.03 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview9.19412.4__
Microsoft.NetCore.App __3.0.0-preview8-28379-05__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview9.19412.8__
Microsoft.NetCore.App __3.0.0-preview8-28379-05__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/b9584d56d8b7eac2f257f1c9bf3a424c6dc0456d...eb966eb60581be3cda3670c866f7194755af8605

**Comment by sebastienros** [comment]
False positive
