### ISSUE TITLE
Can't enable only the Plaintext scenario

### ISSUE THREAD

**Issue by svick** [aspnet/benchmarks#131]
When I try to enable the `Plaintext` scenario, either by using `-- scenarios plaintext` or by typing `plaintext` when prompted, the `MvcPlaintext` scenario is enabled too.

When I enable the default scenarios (`--scenarios [default]`), the `Plaintext` scenario is enabled, but the `Json` scenario is enabled too.

Is it an issue, that it's impossible to enable only the scenario that I want? Is it going to have effect on benchmark results?

**Comment by mikeharder** [comment]
There should be no impact to having either Plaintext and JSON or Plaintext and MvcPlaintext enabled.
