### ISSUE TITLE
Client-side SignalR Telemetry

### ISSUE THREAD

**Issue by bradygaster** [aspnet/Benchmarks#1342]
Internal customers have requested we add telemetry to the benchmarks site that would provide insight on how SignalR client applications perform. Ideally we could report on the following items: 

* CPU
* Memory Usage
* Power Consumption

It'd be good if we could show these numbers with a heavy load of connections and traffic flowing, as well as scenarios in which the clients are idle.

**Comment by davidfowl** [comment]
@BrennanConroy this is done now right?

**Comment by BrennanConroy** [comment]
It's closer, shouldn't say it's done until we actually start doing runs and getting numbers.

**Comment by DamianEdwards** [comment]
Closing this out due to age. Feel free to open a new issue if required.
