### ISSUE TITLE
Performance regression: Plaintext, Json, JsonPlatform

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#1344]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Windows, http, KestrelSockets | 2019-08-27 13:39:46Z | 760235 | 701868 | -7.68 % | -3.42 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc1.19424.9__
Microsoft.NetCore.App __3.0.0-preview9-19410-12__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc1.19426.1__
Microsoft.NetCore.App __3.0.0-preview9-19410-12__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/ec52b9d4d0a34e08768da3b5b4090a8c42351f99...b496781792dc16259d7a25fd29f5c1e4da6ebe78

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| JsonPlatform | Windows, http, KestrelSockets | 2019-08-27 13:38:57Z | 768986 | 716135 | -6.87 % | -2.37 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc1.19424.9__
Microsoft.NetCore.App __3.0.0-preview9-19410-12__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc1.19426.1__
Microsoft.NetCore.App __3.0.0-preview9-19410-12__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/ec52b9d4d0a34e08768da3b5b4090a8c42351f99...b496781792dc16259d7a25fd29f5c1e4da6ebe78

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Plaintext | Windows, https, KestrelSockets | 2019-08-27 13:44:48Z | 2714148 | 2398258 | -11.64 % | -6.16 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-rc1.19424.9__
Microsoft.NetCore.App __3.0.0-preview9-19410-12__

After versions:
Microsoft.AspNetCore.App __3.0.0-rc1.19426.1__
Microsoft.NetCore.App __3.0.0-preview9-19410-12__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/ec52b9d4d0a34e08768da3b5b4090a8c42351f99...b496781792dc16259d7a25fd29f5c1e4da6ebe78

**Comment by benaadams** [comment]
I assume this wasn't from changing SqlClient (as per the commit diff)?

Quite a drop

![image](https://user-images.githubusercontent.com/1142958/63820901-f1026000-c942-11e9-827d-a5bd8d65c0fc.png)
![image](https://user-images.githubusercontent.com/1142958/63821034-65d59a00-c943-11e9-83c3-cdc939881392.png)


Plaintext platform shows and increase in lock contention

![image](https://user-images.githubusercontent.com/1142958/63820970-24dd8580-c943-11e9-8479-58da70f0670e.png) 

As does Plaintext

![image](https://user-images.githubusercontent.com/1142958/63820989-3b83dc80-c943-11e9-84dd-d55a94e0f8c7.png)

/cc @sebastienros @davidfowl
