### ISSUE TITLE
CCore results not reported correctly

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Benchmarks#1423]
CCore results show up with "sockets" in graph. When both CCore and KestrelSockets are selected their results are merged together in the graph.

![image](https://user-images.githubusercontent.com/303201/65680763-bc053c80-e0ab-11e9-9bd5-84c1feddb416.png)

**Comment by sebastienros** [comment]
Ah, I need to update the "Legend" field to concatenate this new value. Will be easy.
