### ISSUE TITLE
How to run the Fortunes platform benchmarks?

### ISSUE THREAD

**Issue by adamsitnik** [aspnet/Benchmarks#1478]
I've created a following `.json` file:

```json
{
  "Default": {
    "Client": "Wrk",
    "PresetHeaders": "html",

    "Source": {
      "Repository": "https://github.com/aspnet/benchmarks.git",
      "BranchOrCommit": "master",
      "Project": "src/BenchmarksApps/Kestrel/PlatformBenchmarks/PlatformBenchmarks.csproj"
    },
    "BuildArguments": [ "/p:IsDatabase=true" ]
  },
  "SingleQueryPlatform": {
    "Path": "/db"
  },
  "FortunesPlatform": {
    "Path": "/fortunes"
  },
  "UpdatesPlatform": {
    "Path": "/updates/queries="
  },
  "MultipleQueriesPlatform": {
    "Path": "/queries/queries="
  }
}
```

And tried to run it using following command:

```cmd
--jobs ..\BenchmarksApps\Kestrel\PlatformBenchmarks\benchmarks.html.json --scenario "FortunesPlatform" --database "PostgreSql"
```

The problem was that the `Database` enum was not set and it was still using the default connection string:

https://github.com/aspnet/Benchmarks/blob/44120672f4f2710318f50d3934675678cde45b2a/src/BenchmarksApps/Kestrel/PlatformBenchmarks/Program.cs#L51

```cs
Database: None
```

So I've tried to set both settings using:

```cmd
--arg "/Database=PostgreSql" --arg "/ConnectionString=Secret"
```

Which has set both settings, but now I am getting another error:

```log
Kestrel Platform-Level Application
/fortunes
/db
/updates/queries=
/queries/queries=
Database: PostgreSql
Hosting environment: Production
Content root path: /tmp/benchmarks-agent/benchmarks-server-6/cobcivyn.pgv/Benchmarks-1/src/BenchmarksApps/Kestrel/PlatformBenchmarks/published/
Now listening on: $secret
Application started. Press Ctrl+C to shut down.

[04:42:40.564] {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"0HLURIERIGSAP:00000004"}
[04:42:40.569] Job halted by the client
[04:42:41.494] Job forcibly stopped on the client, halting driver
[04:42:41.747] Deleting scenario FortunesPlatform on benchmark client...
[04:42:42.167] Starting scenario FortunesPlatform on benchmark client...
```

@sebastienros Do you have any idea what I am doing wrong?

**Comment by adamsitnik** [comment]
I've taken a look at a profile and it looks like the NpgSql client throws an exception when we are trying to set the connection string. 

I've also added logging of it to the output and it looks like the connection string is trimmed to the first space, despite the fact that I have escaped it with `"`

Example:

```cmd
--arg "/ConnectionString=Database=hello_world;Maximum Pool Size=256"
```

```log
Database: None
ConnectionString: Database=hello_world;Maximum
```

**Comment by benaadams** [comment]
The TE version copies the `appsettings.postgresql.json` or `appsettings.mysql.json` from the regular benchmarks and overwrites the local `appsettings.json`

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/CSharp/aspnetcore/aspcore-ado-pg.dockerfile

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.101 AS build
WORKDIR /app
COPY PlatformBenchmarks .
RUN dotnet publish -c Release -o out /p:IsDatabase=true

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2 AS runtime
ENV ASPNETCORE_URLS http://+:8080
WORKDIR /app
COPY --from=build /app/out ./
COPY Benchmarks/appsettings.postgresql.json ./appsettings.json

ENTRYPOINT ["dotnet", "PlatformBenchmarks.dll"]
```

Though not sure how the regular benchmarks work on db switching here

**Comment by roji** [comment]
I do run my benchmarks with `--database PostgreSQL` (and also `-j ../Benchmarks/benchmarks.html.json -n DbFortunesRaw`). I haven't really needed to override the connection string from the cmdline though... Ping me offline and I can try to help you out.

**Comment by adamsitnik** [comment]
@roji what you are running are regular fortunes benchmarks, while there are also platform benchmarks that have the lowest possible overhead of ASP.NET Core (they use "bare metal" ASP.NET Core). I've also learned quite recently about the existence of these benchmarks, so far they were living in a separate repo ;) I want to run these benchmarks and profile them to see if there is something on our (libraries/runtime) side that we could do better to reach to 5.0 goals.

**Comment by roji** [comment]
> there are also platform benchmarks that have the lowest possible overhead of ASP.NET Core

Oh, I thought that's what the "regular" middleware (non-MVC) benchmarks were about... So yeah, I'm unaware of these (and @sebastienros is probably your best friend here :))

**Comment by adamsitnik** [comment]
I've fixed that via https://github.com/aspnet/Benchmarks/pull/1479 (we were not escaping arguments passed via `--arg`  ;) )

BTW @roji some interesting numbers:

### FortunesPlatform 

```log
RequestsPerSecond:           289,589
Max CPU (%):                 98
WorkingSet (MB):             499
Avg. Latency (ms):           1.37
Startup (ms):                1
First Request (ms):          399.83
Latency (ms):                0.29
Total Requests:              4,372,692
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             3,501
Published Size (KB):         1,916
SDK:                         5.0.100-preview.2.20120.3
Runtime:                     5.0.0-preview.4.20205.13
ASP.NET Core:                5.0.0-preview.4.20206.19
```

### SingleQueryPlatform 

```log
RequestsPerSecond:           326,008
Max CPU (%):                 98
WorkingSet (MB):             460
Avg. Latency (ms):           1.25
Startup (ms):                1
First Request (ms):          409.62
Latency (ms):                0.29
Total Requests:              4,922,675
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             3,501
Published Size (KB):         1,916
SDK:                         5.0.100-preview.2.20120.3
Runtime:                     5.0.0-preview.4.20205.13
ASP.NET Core:                5.0.0-preview.4.20206.19
```

### UpdatesPlatform

```log
RequestsPerSecond:           103,000
Max CPU (%):                 84
WorkingSet (MB):             488
Avg. Latency (ms):           2.51
Startup (ms):                1
First Request (ms):          417.18
Latency (ms):                0.56
Total Requests:              1,555,247
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             3,001
Published Size (KB):         1,916
SDK:                         5.0.100-preview.2.20120.3
Runtime:                     5.0.0-preview.4.20209.1
ASP.NET Core:                5.0.0-preview.4.20206.19
```

### MultipleQueriesPlatform

```log
RequestsPerSecond:           319,724
Max CPU (%):                 98
WorkingSet (MB):             725
Avg. Latency (ms):           1.42
Startup (ms):                1
First Request (ms):          405.74
Latency (ms):                0.48
Total Requests:              4,827,719
Duration: (ms)               15,100
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             3,501
Published Size (KB):         1,916
SDK:                         5.0.100-preview.2.20120.3
Runtime:                     5.0.0-preview.4.20209.1
ASP.NET Core:                5.0.0-preview.4.20206.19
```

**Comment by roji** [comment]
@adamsitnik can you provide info on running these platform benchmarks?

**Comment by adamsitnik** [comment]
> can you provide info on running these platform benchmarks?

It's https://github.com/aspnet/Benchmarks/pull/1479#issue-401478504 + secret connection string that I;ve just sent you on Teams

**Comment by benaadams** [comment]
Aside "updates" for postgresql and all scenarios on TE has a slightly different connection string with `Maximum Pool Size=64` to limit the concurrency which showed better throughput; whereas all the others are `Maximum Pool Size=256`

**Comment by roji** [comment]
> Aside "updates" for postgresql and all scenarios on TE has a slightly different connection string with Maximum Pool Size=64 to limit the concurrency which showed better throughput; whereas all the others are Maximum Pool Size=256

FWIW the pool size would change, likely in a pretty dramatic way once multiplexing is implemented - far fewer connections are needed as the driver pipelines and coalesces many more queries into just a few connections. I really hope to be back with a finalized version in a couple weeks.
