### ISSUE TITLE
20k drop in ConnectionClose benchmarks around 16th Jan

### ISSUE THREAD

**Issue by benaadams** [aspnet/Benchmarks#1487]
Any reason for this? Most dramatic on Linux

![image](https://user-images.githubusercontent.com/1142958/79277181-3ad39280-7ea1-11ea-960e-e03994928eaa.png)

However, smaller drops on Windows and https for both platforms

**Comment by sebastienros** [comment]
First think would be to compare with 3.1. I don't remember any special change at this date.

**Comment by sebastienros** [comment]
I get the same perf with 3.1 and 5.0 preview4, so it must be related to the system. 50% cpu
I get 25k on the "perf" environment (12 cores), 92% cpu.
