### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1495]
- Split repository
  - [ ] aspnet/benchmarks
    - We put the benchmark apps here
  - [x] aspnet/perf
    - Infrastructure for benchmarks (driver etc)

- CI/CD
  - Testing
    - [ ] Infrastructure
      - [ ] Start two local agents
      - [ ] Docker image and csproj
    - Apps
      - [ ] Each app should be tested
  - [ ] Docker image for Agent
  - [ ] Global tools (controller + agent)

- Documentation for the infrastructure
  - [x] README
    - [x] New driver only
    - [ ] docs, samples
 
- Refactoring
  - Naming
    - [x] Benchmarks Agent
    - [x] Benchmarks Controller
    - [ ] Benchmarks Relay
  - [x] Simpler arguments for Agent when running locally
    - No arguments necessary
    - Automatic available port detection

- Plugins
   - [ ] Wrk plugin
   - [ ] Bombardier plugin

**Comment by davidfowl** [comment]
Moving this to the actual repo https://github.com/aspnet/perf/issues/9
