### ISSUE TITLE
Enable collection of new EventCounters in Kestrel 

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Benchmarks#1513]
We just added new EventCounters in Kestrel. We should enable collecting them in our perf runs
https://github.com/dotnet/aspnetcore/pull/21649

----
`[EventSource(Name = "Microsoft-AspNetCore-Server-Kestrel")]`
```
connections-per-second
total-connections
tls-handshakes-per-second
total-tls-handshakes
current-tls-handshakes
failed-tls-handshakes
current-connections
connection-queue-length
request-queue-length
current-upgraded-requests
```

**Comment by leonids2005** [comment]
request-queue-length

why it does not work with HTTP/1?  Actually, this information is not clearly stated in the docs :(.
