### ISSUE TITLE
Does not compile with MSVS 2019 Preview .NET 5

### ISSUE THREAD

**Issue by markus27183** [aspnet/Benchmarks#1542]
I get only 1 error: 
rzc generate exited with code 1
According to https://github.com/dotnet/aspnetcore/issues/19480  this is because the latest Blazor is not used in this project.

**Comment by markus27183** [comment]
it still doesn't compile.  Which version of MSVS should I use to open this?

**Comment by DamianEdwards** [comment]
This repo generally requires the latest version of Visual Studio Preview (2022 17.6.0 Preview 2.0 at time of writing).
