### ISSUE TITLE
WrkClient seems to not support low number of connections

### ISSUE THREAD

**Issue by adamsitnik** [aspnet/Benchmarks#1543]
I want to calculate the TechEmpower "Composite Score" for .NET Core 5.0 and 3.1.

I realized that the `Updates` and `Multiple queries` benchmarks use only up to 20 connections and to mimic exactly what TE is doing I've set 20 connections for `wrk`.

It does not work for both Driver and Driver**2**:

```log
RequestsPerSecond:           0
Max CPU (%):                 0
WorkingSet (MB):             73
Avg. Latency (ms):           -1
Startup (ms):                221
First Request (ms):          33.33
Latency (ms):                0.12
Total Requests:              -1
Duration: (ms)               0
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             18,505
Published Size (KB):         101,665
SDK:                         5.0.100-preview.6.20266.3
Runtime:                     5.0.0-preview.7.20306.3
ASP.NET Core:                5.0.0-preview.7.20308.1
```

```log
## Benchmark:
Requests:             -1
Mean latency (ms):    -1.00
Max latency (ms):     -1.00
Bad responses:        0
Socket errors:        0
Latency 50th (ms):    -1.00
Latency 75th (ms):    -1.00
Latency 90th (ms):    -1.00
Latency 99th (ms):    -1.00
```

It works for `bombardier`, but I don't want to use it to make sure I get numbers as close as possible to what TE is getting.

My only guess is that some part of the parsing logic does not work?

@sebastienros could you please take a look?

/cc @roji

**Comment by sebastienros** [comment]
Can you confirm it's fixed on master?
