### ISSUE TITLE
How to get SDK & runtime versions using Driver2?

### ISSUE THREAD

**Issue by adamsitnik** [aspnet/Benchmarks#1546]
In Driver1 we always get all the versions printed:

```log
SDK:                         5.0.100-preview.6.20266.3
Runtime:                     5.0.0-preview.7.20307.4
ASP.NET Core:                5.0.0-preview.7.20308.12
```

@sebastienros  How can I get them with Driver2?

**Comment by sebastienros** [comment]
The app itself needs to record this value.

Either using an event source:
https://github.com/aspnet/Benchmarks/blob/master/src/BombardierClient/Program.cs#L156

Or a custom json payload on the stdout:
https://github.com/aspnet/Benchmarks/blob/master/src/Benchmarks/Program.cs#L48-L67

The server could emit it as it knows what arguments it configures the app to run with, but it's like Server GC, it's better if it comes from the app itself to be certain about what version it's using.

Also please remember to use `--application.channel edge --application.framework netcoreapp5.0` to be certain that the app is configured to use the latest builds of 5.0. Or it will use the current public ones of the default TFM in the csproj.

**Comment by adamsitnik** [comment]
This is now printed by the Driver:

![obraz](https://user-images.githubusercontent.com/6011991/100456441-a715a600-30c0-11eb-8ff7-bd6f7acc93ea.png)


thank you @sebastienros !
