### ISSUE TITLE
Benchmarks build issue

### ISSUE THREAD

**Issue by aniket-de** [aspnet/Benchmarks#1549]
**Describe the Bug**
Running the build.sh script in the root directory of the repository fails with 3 errors.

**Error messages**
/home/user/.nuget/packages/microsoft.aspnetcore.blazor.build/0.7.0/targets/RazorCompilation.targets(184,5): error : rzc generate exited with code 1. [/home/user/work/performance_asp/src/Benchmarks.UI.App/Benchmarks.UI.App.csproj]

Data/EfDb.cs(96,18): error CS0433: The type 'IAsyncEnumerable<T>' exists in both 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/home/user/work/performance_asp/src/Benchmarks/Benchmarks.csproj]

Data/EfDb.cs(78,60): error CS0433: The type 'IAsyncEnumerable<T>' exists in both 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/home/user/work/performance_asp/src/Benchmarks/Benchmarks.csproj]

**System Info**
OS: Ubuntu 20.04
Kernel: 5.4.0-37-generic
Arch: x86_64

**Dotnet Info**
Ver: 5.0.100-preview.4.20258.7

SDKs: 
2.2.402 [/usr/share/dotnet/sdk]
3.1.301 [/usr/share/dotnet/sdk]
5.0.100-preview.4.20258.7 [/usr/share/dotnet/sdk]

Runtimes:
Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0-preview.4.20257.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comments**
I saw similar bugs on the aspnetcore repository (seemed to be netcore ver issues). Tried building with lower versions (2.2, 3.1) on a different branch (sebros/cpu), but that presented the same error messages.

**Comment by adamsitnik** [comment]
@sebastienros @roji have you run into these errors before? Is `build.sh` expected to work?

**Comment by sebastienros** [comment]
I would not expect it to work. Never use it. And we are working on the new repository now, I'll show it this afternoon on live.asp.net.

**Comment by adamsitnik** [comment]
@aniket-de in such case you might try the following command:

```cmd
dotnet build ./benchmarks.sln
```

**Comment by aniket-de** [comment]
I can build the individual benchmarks components using the scripts in the docker/* folders. I'll stick to using that. Thanks.
