### ISSUE TITLE
Add implementations for new "cached queries" TechEmpower benchmark

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Benchmarks#1556]
From the [requirements](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#caching-work-in-progress):

> ## Caching (Work in progress)
> The Caching test exercises the preferred in-memory or separate-process caching technology for the platform or framework. For implementation simplicity, the requirements are very similar to the multiple database-query test [Test #3](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#multiple-database-queries), but use a separate database table. The requirements are quite generous, affording each framework fairly broad freedom to meet the requirements in the manner that best represents the canonical non-distributed caching approach for the framework. (Note: a distributed caching test type could be added later.)
> 
> This test type is a work-in-progress and may evolve in ways that break implementations. Early implementations are acceptable but not yet encouraged.

I imagine we'll want the following implementations, all using `IMemoryCache`:
- Platform
- Middleware (using routing and endpoints)
- MVC

We might want to consider a set of implementations using Redis as well.

[Tweet showing early results from other frameworks](https://twitter.com/TFBenchmarks/status/1275902644893040640):
![image](https://user-images.githubusercontent.com/249088/85639906-0fa6b580-b63f-11ea-8023-6edb9f030cdf.png)

**Comment by bhauer** [comment]
The results in the tweet above are not suitable for comparison purposes. They were being computed using results from a single cached query (iteration?) rather than the 20-query versions.

The results below are more accurate.

![image](https://user-images.githubusercontent.com/777068/85770738-16c9d400-b6d0-11ea-8db1-348b4fb701a6.png)

We'll tweet again when the results for Round 19 are rendered on the results web site.

**Comment by benaadams** [comment]
Giving it a go for Platform (and updating its urls for round 20); I'll let someone at MS tackle the regular framework variants 😉

**Comment by benaadams** [comment]
I've added a platform benchmarks scenerio https://github.com/aspnet/Benchmarks/pull/1557 and added a draft TE sync with it https://github.com/TechEmpower/FrameworkBenchmarks/pull/5807

It also updates the paths for round 20

Not sure how to add it to the tested scenarios for benchmark BI though

**Comment by sebastienros** [comment]
I added it to the automatic runs and it will appear in the dashboard.
