### ISSUE TITLE
TechEmpower benchmark round 13 - asp.net core not completed even a single benchmark?

### ISSUE THREAD

**Issue by kbugala** [aspnet/benchmarks#156]
I've been waiting for the new benchmark round to see how the new open source dotnet core compares to the other frameworks, but it seems like none of the benchmarks were completed...

Does it mean that the benchmark did not complete or the repo did not comply with the benchmark requirements? I've seen some blog posts mentioning about significant performance improvements of the dotnet core framework but I'm a bit confused now. Can anyone shed a bit more light into the issue?

**Comment by mqueirozcorreia** [comment]
The actual result is a second preview. I was looking at logs I couldn't find anything:
http://tfb-logs.techempower.com/round-13/preview-2/

The result in August/2016 were pretty good! But I can see them anymore too...

If it helps you, there are some results at readme.md:
https://github.com/aspnet/benchmarks/blob/dev/README.md

Anyway, I'm looking forward to see next preview with asp.net core results too. Does anybody know what happened?

**Comment by kbugala** [comment]
It seems like there are 3 previews in the round 13 and that ASPNET CORE did actually pass the tests. Have a look at the raw results (results.json) `http://tfb-logs.techempower.com/round-13/preview-3/`

**Comment by mikeharder** [comment]
The numbers for ASP.NET Core will be included in the final results for Round 13, which will be released soon (https://groups.google.com/d/msg/framework-benchmarks/hsIThZR8Lo4/sHGwzvtyAAAJ).
