### ISSUE TITLE
slow servers report with integers rounded to 0

### ISSUE THREAD

**Issue by RobertHenry6bev** [aspnet/Benchmarks#1575]
I run the benchmarks server on a slow (2MIPs) system.  That exposes some rounding errors in the output

Consider the out put below. Amost everything in this list (except integer counts total requests, bad responses and socket errors) should be gathered as a float, and then printed as a float.  I suspect RequestsPerSecond is, say, 0.1, which if rounded and printed as an integer, gives me 0.

03:32:11.180] Deleting scenario DbSingleQueryRaw on benchmark client...
RequestsPerSecond:           0
Max CPU (%):                 97
WorkingSet (MB):             62
Avg. Latency (ms):           -1
Startup (ms):                6746
First Request (ms):          0
Latency (ms):                0
Total Requests:              0
Duration: (ms)               0
Socket Errors:               0
Bad Responses:               0
Build Time (ms):             109,045

**Comment by DamianEdwards** [comment]
Closing this out due to age. Feel free to open a new issue if required.
