### ISSUE TITLE
SQLServer2016 R2 Scenario

### ISSUE THREAD

**Issue by benaadams** [aspnet/Benchmarks#159]
Now SQLServer2016 SP1 is available on both Windows and Linux and even the Express edition has the fancy features<sup>1</sup>; it would be good to have a scenario that used it as the database and In-Memory OLTP. 

(Data Compression and Column Store is probably worth a look too; though I'd guess it won't make much difference as the datasets are small).

<sup>[1]</sup> https://sqlperformance.com/2016/11/sql-server-2016/big-deal-sp1

/cc @DamianEdwards

**Comment by Drawaes** [comment]
Yes! This 100* .

As for compression I have yet to see it used in the wild and I expect it will add more overhead so I wouldn't bother

**Comment by sebastienros** [comment]
FYI we already measure Sql Server, MySql and MongoDB, we are just not yet showing them. Thanks to the Docker god for making it super simpler.
