### ISSUE TITLE
[Question] What command line arguments and other configuration is used on the single query aspcore-ado-pg benchmark?

### ISSUE THREAD

**Issue by JesseLambert** [aspnet/Benchmarks#1595]
Hey everyone, we're trying to reproduce one of your benchmarks and are missing some of the necessary configuration to make sense of it. Primarily the:
- hosting.json
- Any environment variables
- Any command line arguments

Could someone possibly share what was used for the aspcore-ado-pg single query benchmark?

**Comment by sebastienros** [comment]
Can you use https://github.com/dotnet/crank to run them?

The configuration of the Benchmarks app is defined in this file:
https://github.com/aspnet/Benchmarks/blob/master/scenarios/database.benchmarks.yml#L20-L22

With crank you can run the scenario directly, example: https://github.com/aspnet/Benchmarks/tree/master/scenarios#available-scenarios-3

**Comment by sebastienros** [comment]
I just added the configuration to run the scenario you are asking for with crank:
https://github.com/aspnet/Benchmarks/tree/master/scenarios#available-scenarios-2

It means this command line would work, as long as you define your own "profile" in another configuration file:

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/master/scenarios/database.benchmarks.yml --scenario single_query --profile [YOUR_PROFILE_HERE]
```

**Comment by benaadams** [comment]
If you specifically want the one in TechEmpower its defined in the [`aspcore-ado-pg.dockerfile`](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/CSharp/aspnetcore/aspcore-ado-pg.dockerfile) file 
```yml
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
COPY PlatformBenchmarks .
RUN dotnet publish -c Release -o out /p:IsDatabase=true

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
ENV ASPNETCORE_URLS http://+:8080
WORKDIR /app
COPY --from=build /app/out ./
COPY PlatformBenchmarks/appsettings.postgresql.json ./appsettings.json

ENTRYPOINT ["dotnet", "PlatformBenchmarks.dll"]
```
So latest on continuous runs is published in release mode with .NET 5.0 and the `IsDatabase=true` define
`dotnet publish -c Release -o out /p:IsDatabase=true`

Then the only environment variable set is `ASPNETCORE_URLS` and the `appsettings.json` settings used which define the postgres connection string are in the repository's [`appsettings.postgresql.json`](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/CSharp/aspnetcore/PlatformBenchmarks/appsettings.postgresql.json)
```json
{
  "ConnectionString": "Server=tfb-database;Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=256;NoResetOnClose=true;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Delay Us=500;Write Coalescing Buffer Threshold Bytes=1000",
  "Database": "postgresql"
}
```

**Comment by JesseLambert** [comment]
I'm still having some difficulties determining where you're pulling some config values such as server, protocal and KestrelTransport. At the moment we're not interested in running the application ourselves, we're simply trying to follow the code path of the startup/program.cs file to determine if it falls in line with what we have implemented so far.

**Comment by DamianEdwards** [comment]
Closing this out due to age. Feel free to open a new issue if required.
