### ISSUE TITLE
Cannot get higher than 13k RPS using Kestrel on Windows 7

### ISSUE THREAD

**Issue by NimaAra** [aspnet/benchmarks#161]
I am running the benchmarks using _kestrel_ (current trunk with no modification) but I cannot go higher than ~13k RPS on the _plaintext_. 

Even though I am running both the client/server locally I still tried fiddling with the firewall so:

* I have tried disabling the firewall;
* I have tried opening the _5000_ port for _TCP_ on the firewall;
* I have tried running it on different machines and different networks;

I can see only _%5-%8_ _CPU_ utilization half of which is in kernel mode. Bandwidth utilization is _~15mbit_, so plenty of room for the server to serve more requests.

I have tried different machines, here are some specs:

### Machine 1:
```
Windows 7 x64 Enterprise
i7-4770 @3.50GHz 8 Cores (HT)
16GB RAM
Gigabit Ethernet
```
### Machine 2:
```
Windows 7 x64 Enterprise
2x Intel Xeon E5-2620V2 24 Cores (HT)
48GB RAM
Gigabit Ethernet
```

In fact, in the more beefier machine (_Machine 2_) I am getting _~6000 RPS_!

I have tried both _ab.exe_ and _Netling_ for load generation. Both using 8 to 24 concurrent threads.

What have I overlooked?

**Comment by benaadams** [comment]
That's quite low. Try using this as the application 

`project.json`
```json
{
  "version": "1.1.0-*",
  "dependencies": {
    "Microsoft.AspNetCore.Server.Kestrel": "1.2.0-*"
  },
  "buildOptions": {
    "emitEntryPoint": true
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0-*"
        }
      }
    }
  }
}
```
`Program.cs`
```csharp
public class Startup
{
	private static readonly byte[] _helloWorldPayload = Encoding.UTF8.GetBytes("Hello, World!");

	public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
	{
		app.Run((context) =>
		{
			var response = context.Response;
			response.StatusCode = 200;
			response.ContentType = "text/plain";
			response.Headers["Content-Length"] = "13";
			return response.Body.WriteAsync(_helloWorldPayload, 0, _helloWorldPayload.Length);
		});
	}

	public static void Main(string[] args)
	{
		var host = new WebHostBuilder()
			.UseKestrel()
			.UseUrls("http://localhost:5000/")
			.UseContentRoot(Directory.GetCurrentDirectory())
			.UseStartup<Startup>()
			.Build();

		host.Run();
	}
}
```
To make sure you don't have an issue saturating bandwidth; you can change this the following; which should saturate bandwidth rather than test requests per second:

```csharp
	private static readonly byte[] _payload = new byte[4000];

	public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
	{
		app.Run(async (context) =>
		{
			var response = context.Response;
			response.StatusCode = 200;
			response.ContentType = "application/octet-stream";
			response.Headers["Content-Length"] = "8000000";
                        for (var i = 0; i < 2000; i++) {
			    await response.Body.WriteAsync(_payload, 0, 4000);
                        }
		});
	}
```

Is receive side scaling (RSS) enabled on the network cards?

Try the following for ab
```ab -q -k -c 256 https://server:5000/``` (swapping `server` for the server ip)

With Netling try pipelining 16, increasing the number of threads to 8 per core and setting thread affinity.

Also when you say locally; do you mean `127.0.0.1` on the same machine? If so that isn't very reliable - especially on Windows 7, and the two processes are competing for resources - try doing it between two different machines.

**Comment by NimaAra** [comment]
Thanks @benaadams, by locally I meant _https://localhsot:5000_.

_RSS_ is _Window Server_ only no? and as for pipelining, it is not available on _Windows 7_.

In fact I just reran the benchmarks on a _Windows Server 2012_ and I get around _~300K_ with a pipelining depth of _8_ and _24_ concurrent threads but I guess I should move my client to another machine to get higher _RPS_ as the CPU is currently maxed out.  

I will try your suggestions to see if I can go higher on _Windows 7_.

So I guess this maybe that benchmarks should not be run on a **non _Windows Server_**, has anyone ever tried getting high _RPS_ on _Windows 7_?

**Comment by mikeharder** [comment]
A few general tips:

1. Use separate machines for the load generator and web server.  One reason is to avoid having them compete for resources.  Another reason is the localhost network interface has different performance characteristics than a physical network interface.
2. Ensure the load generator is capable of saturating the server.  TechEmpower uses wrk (https://github.com/wg/wrk) on Linux, which is typically able to saturate the server if the load generator and server are the same size.  Other load generators may hit their own bottleneck before saturating the server, especially for high-throughput tests like Plaintext.
3. We test performance on Windows Server and Ubuntu Server.  If you wanted to compare Windows 7 to Windows Server, you would need to run both on the same hardware and use the same load generator.

**Comment by NimaAra** [comment]
@mikeharder, thanks for the tips however given the significant performance difference I am getting between _Windows 7_ and _Windows Server_ I don't really think they apply to the issue I am facing.

I am only getting _%5-%8_ _CPU_ utilization and _~15mbit_ bandwidth utilization so plenty of room before I get anywhere near saturating _CPU_ and/or bandwidth on _Windows 7_.

@benaadams I tried your suggestions by enabling _RSS_ and using the suggested configs for both _Netling_ and _AB.exe_ which resulted in slightly larger _RPS_ (_~17k_) but still nowhere near what I am getting on _Windows Server_ (_~300k_).

Just as an FYI, switching from _Kestrel_ to _WebListener_ and/or _HttpListener_ or using _Katana_ with _HttpListener_ also results in _~17k_ on _Windows 7_ and _~30K_ on _Windows Server_. I guess there is a hard limit somewhere being enforced by _Windows 7_.

**Comment by benaadams** [comment]
@NimaAra you are also comparing two different generations of OS

Windows server 2012 is Windows 8's generation - it wasn't all about the Metro UI  :) Were some good advancements in networking. Windows 7 is Windows server 2008's generation. (Windows server 2016/Nano server bring further advances)

**Comment by NimaAra** [comment]
@benaadams , I just ran the same on a _VM_ with inferior _CPU_ and _RAM_ than my physical machines running _Windows Server 2008 R2 SP 1_ and I am getting _~250k_ RPS so this is all telling me _Windows 7_ is being throttled :-(

**Comment by benaadams** [comment]
Windows 7 is limited to 20 inbound connections (was 10 on previous OSs) as it is a desktop rather than server OS

**Comment by NimaAra** [comment]
Aaah of course! I remember @DamianEdwards mentioned this a few years back when he was talking about load testing _SignalR_.

Running `winver` does actually confirm:

![winver](http://windowsitpro.com/site-files/windowsitpro.com/files/archive/windowsitpro.com/content/content/129322/122710-winver-3f-win7.jpg)
