### ISSUE TITLE
Job failed on benchmark server, stopping... Job failed at runtime: [STDERR] {0x18db-0x14e731761390} ASSERT [DCI_NUMA] at ./runtime/src/coreclr/src/pal/src/numa/numa.cpp.267: Expression: st == 0

### ISSUE THREAD

**Issue by mayadav1** [aspnet/Benchmarks#1611]
Facing error while running plaintext scenario with net6.0.
command used to run scenario:
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/master/scenarios/plaintext.benchmarks.yml --scenario plaintext --profile local --application.framework net5.0 --application.channel current --application.options.outputFiles ./runtime/artifacts/bin/testhost/\*\* --output plaintext

Error:
Job failed at runtime:
[STDERR] {0x18db-0x14e731761390} ASSERT [DCI_NUMA] at /home/amd/manoj/project2/runtime/src/coreclr/src/pal/src/numa/numa.cpp.267: Expression: st == 0

Please help over it.

**Comment by DamianEdwards** [comment]
Closing this out due to age. Feel free to open a new issue if required.
