### ISSUE TITLE
Update Benchmarks.csproj connection string

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1612]
Add multiplexing, same as Platform benchmarks

**Comment by benaadams** [comment]
Might want to try a few variants of the parameters? Platform's current settings weren't determined on citrine; could be better values.

**Comment by sebastienros** [comment]
It's just that we have discrepancies in the charts and this is one variable that adds some doubts when we see a regression.

**Comment by benaadams** [comment]
Not long left for TE Round 20 if there are better multiplexing values

![image](https://user-images.githubusercontent.com/1142958/102132187-2ccc7c00-3e4b-11eb-8409-5e60937017f6.png)

**Comment by DamianEdwards** [comment]
Pretty sure this was done.
