### ISSUE TITLE
Track YARP on .NET 5.0

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Benchmarks#1618]
YARP is still targeting .NET 5.0 for its initial release and we want to track what the customer experience will be for that .NET version. This can be tracked separately from the .NET Latest numbers.

**Comment by Tratcher** [comment]
Completed by Miha.

**Comment by sebastienros** [comment]
First results, on 10KB, http-http

![image](https://user-images.githubusercontent.com/1165805/108245280-f211e900-7104-11eb-920f-9de391e26cc1.png)
