### ISSUE TITLE
Add pipelines plaintext benchmark

### ISSUE THREAD

**Issue by davidfowl** [aspnet/benchmarks#164]
We need to add a plaintext benchmark with pipelines + .NET Sockets. This relies on us taking in some new CLR bits 4.4.0-* which we don't do yet.

/cc @pranavkm @pakrym

**Comment by aL3891** [comment]
don't forget rio :)

**Comment by davidfowl** [comment]
We decided to pause on this until we get a decoupled http parser from kestrel
