### ISSUE TITLE
[Windows] Regression in few TechEmpower benchmarks

### ISSUE THREAD

**Issue by adamsitnik** [aspnet/Benchmarks#1668]
I wanted to provide some nice benchmark results for @maryamariyan who is currently writing the blog post about `Microsoft.Extensions*`  improvements we did for .NET 6.

To my surprise, the `CachingPlatform-intel-win` has regressed from 290k+ to 270k RPS. 

 `Plaintext-intel-win` has also regressed from 540k to 500k:

![obraz](https://user-images.githubusercontent.com/6011991/117426943-c7c21180-af24-11eb-858c-461d5893ee3c.png)

I've taken a very quick look at the profiles and noticed something that I've not seen before: a LOT of time spent in very expensive [event logging](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs#L514-L515):

![obraz](https://user-images.githubusercontent.com/6011991/117428368-4a979c00-af26-11eb-99ff-c2479a4fa622.png)

Repro:

```cmd
git clone https://github.com/aspnet/Benchmarks.git repro
crank --config .\repro\scenarios\platform.benchmarks.yml --scenario caching --profile aspnet-perf-win --application.collect true
```

@sebastienros @davidfowl : do we know about the regressions and what has caused them? is the expensive logging always enabled, or just when profiling? how can I disable it?

cc  @jeffhandley

**Comment by davidfowl** [comment]
I'm pretty sure it's only enabled when you turn profiling on.

**Comment by benaadams** [comment]
What's the stack before eventsource? What method is doing the emitting?

**Comment by adamsitnik** [comment]
@benaadams 
![obraz](https://user-images.githubusercontent.com/6011991/117449839-bab31b80-af40-11eb-80ca-0fce7cb8c7f5.png)

**Comment by benaadams** [comment]
Looks like runtime issue? `FrameworkEventSource.Log.ThreadPoolEnqueueWorkObject` which is gated on `loggingEnabled && FrameworkEventSource.Log.IsEnabled()` [ThreadPoolWorkQueue.cs#L514-L515](https://github.com/dotnet/runtime/blob/55b613ceed351c5255e8cf38e03d6f7856491b79/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs#L514-L515)

Which is set as [ThreadPoolWorkQueue.cs#L440-L443](https://github.com/dotnet/runtime/blob/55b613ceed351c5255e8cf38e03d6f7856491b79/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs#L440-L443)
```
loggingEnabled = FrameworkEventSource.Log.IsEnabled(EventLevel.Verbose, FrameworkEventSource.Keywords.ThreadPool | FrameworkEventSource.Keywords.ThreadTransfer);
```

I did have issue with VS triggering machine-wide verbose listing on `FrameworkEventSource` https://github.com/dotnet/runtime/issues/49592; but I assume that's not the issue on Citrine?

**Comment by benaadams** [comment]
Still probably should be logging threadpool events at `EventLevel.Verbose` :)

**Comment by danmoseley** [comment]
How much micro benchmark coverage do we have for Extensions - especially logging?

**Comment by benaadams** [comment]
> How much micro benchmark coverage do we have for Extensions - especially logging?

From the traces this is specifically EventSource which looks like people are running benchmarks for https://github.com/dotnet/runtime/pull/52092, though don't know if they are in the perf repo (as it probably should be logging anything for these events unless it was switched on in Perfview specifically)

**Comment by adamsitnik** [comment]
@sebastienros how can I disable the events to get a clean trace file?

**Comment by adamsitnik** [comment]
> How much micro benchmark coverage do we have for Extensions 

I would say that it's OK, we have dedicated micro benchmarks for Caching, DI, Http, Logging and Primitives.


> especially logging?

35 benchmarks: https://github.com/dotnet/performance/tree/main/src/benchmarks/micro/libraries/Microsoft.Extensions.Logging

but here the problematic logging is ETW logging, not `Microsoft.Extensions.Logging`

**Comment by sebastienros** [comment]
@adamsitnik if this can be set as perfview arguments, here is the one to change:

```
--[JOB].collectArguments <arguments>                                     

Native traces arguments, default is "BufferSizeMB=1024;CircularMB=4096;TplEvents=None", other suggested values: "BufferSizeMB=1024;CircularMB=4096;ThreadTime", "BufferSizeMB=1024;CircularMB=4096;GcOnly"
```

**Comment by benaadams** [comment]
So the defaults shouldn't be triggering the `EventLevel.Verbose, FrameworkEventSource.Keywords.ThreadPool | FrameworkEventSource.Keywords.ThreadTransfer` might be accidently triggered?

**Comment by davidfowl** [comment]
cc @brianrob

**Comment by brianrob** [comment]
Yeah, this looks like it's due to the fact that profiling is enabled.  You can confirm that something else isn't causing this by explicitly disabling these events.  With Perfview, try `/ClrEvents:None /TPLEvents:None`.  If it still shows up, then something else is enabling them.

@benaadams, there is an incoming change to address the issue that you saw with VS, that will limit the collection to just `devenv.exe`.

**Comment by benaadams** [comment]
> Yeah, this looks like it's due to the fact that profiling is enabled.

Should it be recording every queued ThreadPool item by default? (e.g. verbose); As that will be millions of events per second?

**Comment by brianrob** [comment]
No, it should not be.  I think that this environment uses a cached version of PerfView that used to do this, but the latest version should not.

**Comment by adamsitnik** [comment]
> With Perfview, try /ClrEvents:None /TPLEvents:None

I have tried that:

```cmd
crank --config .\scenarios\platform.benchmarks.yml --scenario caching --profile aspnet-citrine-win --application.collect true --application.collectArguments "BufferSizeMB=1024;CircularMB=4096;TplEvents=None;ClrEvents=None"
```

But for some reason, it ends up with more than 90% of broken stacks:

![obraz](https://user-images.githubusercontent.com/6011991/117616586-98e9ac80-b16b-11eb-9091-a626eb8761de.png)

I've tried to extend the rundown time, but it did not help:

```cmd
 --application.collectArguments "BufferSizeMB=1024;CircularMB=4096;TplEvents=None;ClrEvents=None;MinRundownTime=120"
```

All I get are native call stacks.

>  I think that this environment uses a cached version of PerfView that used to do this, but the latest version should not.

@sebastienros could you please update PerfView to latest version?

**Comment by sebastienros** [comment]
Updated from 2.0.66 to 2.0.68.

**Comment by brianrob** [comment]
@adamsitnik, sorry that's because the command I gave you shutoff unwind info publish.  Try `/ClrEvents:JitSymbols`.  Also, it looks like @sebastienros has updated to the latest version of PerfView, so it might be worth just trying the default collection args.

**Comment by adamsitnik** [comment]
With `TplEvents=None;ClrEvents:JitSymbols` I still get a complain about 90%+ stacks being BROKEN, but ETW is gone from the trace.

```cmd
--application.collectArguments "BufferSizeMB=1024;CircularMB=4096;TplEvents=None;ClrEvents:JitSymbols"
```

**Comment by sebastienros** [comment]
`asp-perf-win` didn't have the PerfView update, now it has it.

**Comment by adamsitnik** [comment]
I've updated crank and run the benchmarks again. I am still seeing the same issue:

![obraz](https://user-images.githubusercontent.com/6011991/117853319-8d3fd800-b288-11eb-9681-035b5b9d8ad3.png)

**Comment by benaadams** [comment]
Tracing is throwing exceptions for some reason? https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-exraisedatatypemisalignment

> The ExRaiseDatatypeMisalignment routine can be used with structured exception handling to throw a driver-determined exception for a misaligned data type that occurs when a driver processes I/O requests.

**Comment by adamsitnik** [comment]
I've narrowed down the regression to https://github.com/dotnet/runtime/pull/50778 and opened an issue in the runtime repo: https://github.com/dotnet/runtime/issues/52640

I am not closing this issue yet as it would be great to clarify why `ExRaiseDatatypeMisalignment` happens to take so much time on Windows (cc @brianrob)

**Comment by DamianEdwards** [comment]
Closing this issue due to age. Feel free to reopen if this is still a priority.
