### ISSUE TITLE
FortunesPlatform broken on 3.1

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1675]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1133106&view=logs&j=8d35e39b-1b74-5d6c-7d34-86446a0e83a3&t=4bc7bc3a-2a3e-5775-bab2-c105bd9450b9

/cc @roji

**Comment by roji** [comment]
Will investigate and fix.

**Comment by sebastienros** [comment]
Note the fix is probably obvious, but busy with other things right now, and not critical (3.1)

**Comment by DamianEdwards** [comment]
Not relevant anymore
