### ISSUE TITLE
Database scenarios failing on Ubuntu 20.04

### ISSUE THREAD

**Issue by alexcovington** [aspnet/Benchmarks#1682]
Having some issues trying to run any of the Database scenarios on Ubuntu 20.04. It looks like the `readyStateText` no longer matches the output of the default Postgres container ([link](https://github.com/aspnet/Benchmarks/blob/31c49beccc6725708c47d74e658473fb00905088/scenarios/database.benchmarks.yml#L36)).

Command to reproduce:

```sh
$ crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --profile local --scenario fortunes
```

The `db` job gets stuck in `Starting`.

Output of the Postgres container:

```
[05:27:41.949] [STDERR] 2021-06-16 17:27:41 GMT LOG:  ending log output to stderr
[05:27:41.949] [STDERR] 2021-06-16 17:27:41 GMT HINT:  Future log output will go to log destination ""
```

I am able to successfully run the scenarios if I change `readyStateText` to:

```
    readyStateText: Future log output will go to log
```

**Comment by sebastienros** [comment]
https://github.com/postgres/postgres/blob/master/src/backend/postmaster/postmaster.c#L1111-L1119

Which means that something might have change WRT the destination of the log ...

**Comment by sebastienros** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/commit/9f7be7fb8dd4b411ad65d0f4f5c336b0234ee289
