### ISSUE TITLE
Re-update JSON platform benchmarks to use JSON source generator

### ISSUE THREAD

**Issue by halter73** [aspnet/Benchmarks#1689]
#1683 has been [reverted](https://github.com/aspnet/Benchmarks/pull/1688). We should reapply it once preview7 is available.

**Comment by adamsitnik** [comment]
@davidfowl https://dotnetcli.blob.core.windows.net/dotnet/Sdk/main/latest.version points to 6.0.100-preview.7.21379.14, can we revert #1688 now?

**Comment by sebastienros** [comment]
We can, yes. I changed the source for the sdk to https://aka.ms/dotnet/6.0/daily/productCommit-win-x64.txt currently at 6.0.100-rc.1.21417.19

**Comment by adamsitnik** [comment]
@sebastienros could you please do that? I have no permissions in this repo and I can't click the "Revert" button

**Comment by sebastienros** [comment]
Thanks for teaching me there is a "revert" button on GH, just tried it ;)

**Comment by layomia** [comment]
Looks like this issue can be closed following https://github.com/aspnet/Benchmarks/pull/1698.
