### ISSUE TITLE
Add response caching middleware scenario that bypass the middleware

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/benchmarks#169]
We used to rely on the scenario RequestNoCache to keep track of the performance when the middleware is bypassed. A no-cache on the request shouldn't bypass the middleware, it should just skip the cache look up and has been addressed in https://github.com/aspnet/ResponseCaching/issues/83. 

We need a new scenario that sends a POST request for example.

**Comment by ferantivero** [comment]
aspnet/KestrelHttpServer#1319
