### ISSUE TITLE
Enable .NET 6.0 full PGO?

### ISSUE THREAD

**Issue by roji** [aspnet/Benchmarks#1690]
As per https://github.com/dotnet/runtime/pull/52708#issuecomment-870860458

/cc @sebastienros @benaadams

**Comment by sebastienros** [comment]
Submitted to TE https://github.com/TechEmpower/FrameworkBenchmarks/pull/6830

**Comment by sebastienros** [comment]
We are actually already running the benchmarks with different PGO modes, there is a dedicated page in the PowerBI that lets us compare the result without PGO. Maybe the only thing to add is a few more benchmarks to it.
