### ISSUE TITLE
Power BI - This content isn't available

### ISSUE THREAD

**Issue by EatonZ** [aspnet/Benchmarks#1693]
The link provided [in the readme](https://github.com/aspnet/Benchmarks/blob/main/README.md#benchmarks) to view the benchmark results (https://aka.ms/aspnet/benchmarks) is currently non-functional:

![2021-08-19_16-55-35](https://user-images.githubusercontent.com/3020941/130142892-6b881b68-5fec-48db-bd4f-aaf435bced98.png)

**Comment by sebastienros** [comment]
I see the same problem, but it should be a temporary PowerBI issue, it was working yesterday and we didn't change it. Let's try again later.

**Comment by EatonZ** [comment]
Took a while to sort itself out, but it's working now.
