### ISSUE TITLE
Add benchmarks for "Multiple database queries" using EF7 & MSSQL

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Benchmarks#17]
Requirements are at https://www.techempower.com/benchmarks/#section=code

We should have a middleware version and an MVC version.

**Comment by NickCraver** [comment]
Close via 17b319f3a230fb629bed65e805bb0c3a108d23f6?

**Comment by NickCraver** [comment]
Note: middleware version complete via 17b319f3a230fb629bed65e805bb0c3a108d23f6

**Comment by DamianEdwards** [comment]
Needs the MVC version still.
