### ISSUE TITLE
Unable to run platform benchmarks using local config file

### ISSUE THREAD

**Issue by adamsitnik** [aspnet/Benchmarks#1709]
Repro:

```cmd
git clone https://github.com/aspnet/Benchmarks.git && cd Benchmarks
crank --config .\src\BenchmarksApps\Kestrel\PlatformBenchmarks\platform.benchmarks.yml --scenario caching --profile aspnet-perf-lin
```

Output:

```log
Configuration 'D:\projects\aspnet_benchmarks\https:\raw.githubusercontent.com\aspnet\Benchmarks\main\src\WrkClient\wrk.yml' could not be loaded.
```

cc @sebastienros

**Comment by sebastienros** [comment]
`https:\raw.githubusercontent.com\aspnet\Benchmarks\main\src\WrkClient\wrk.yml` this is not even a thing. I will delete the yml you used, must be an old one. Please check the https://github.com/aspnet/Benchmarks/tree/main/scenarios README for the valid ones.

**Comment by DamianEdwards** [comment]
@adamsitnik seems this is resolved so I'm closing this out. Feel free to reopen if there's still an issue here.
