### ISSUE TITLE
Postgres is not mirroring TE config

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Benchmarks#1712]
There are a few differences causing reduced perf between what we see on TE and the perflab when running identical code. For example data updates diverges as much as 10 to 15%. This is likely due to synchronous commit being off on TE https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/databases/postgres/postgresql.conf#L176 (wal level is also at minimal). 

Differences like these makes it hard to compare improvements, precisely because improvements can be very nonlinear. Anything we are willing to do here?

**Comment by sebastienros** [comment]
We do point to their Docker file for the database benchmarks:

https://github.com/aspnet/Benchmarks/blob/main/scenarios/database.benchmarks.yml#L29-L37

**Comment by roji** [comment]
@NinoFloris it seems like the config you found under docker/postgres-techempower is old and no longer used...

**Comment by NinoFloris** [comment]
@sebastienros Thanks for pointing me in the right direction. For platform that would be https://github.com/aspnet/Benchmarks/blob/main/scenarios/platform.benchmarks.yml#L23-L31 (?), I must have missed the postgres section in the yaml...

Data updates and json are interesting outliers given the perflab usually performs > 10% better than TE, comparing numbers from http://aka.ms/aspnet/benchmarks (I'm aware of some of the differences like full PGO and inline continuations but these gaps have been here for way longer than those features).

I mostly want to rule out any differences in config. Beyond that we may just be looking at some physical variation, identical model numbers never tell the full story.

Until I know more I'll close the issue, thanks!
