### ISSUE TITLE
PGO benchmarks improvements

### ISSUE THREAD

**Issue by EgorBo** [aspnet/Benchmarks#1751]
I couple of improvements for PGO page at https://aka.ms/aspnet/benchmarks

![image](https://user-images.githubusercontent.com/523221/191392056-8a74720a-6e92-4fb1-8587-caa5200c8212.png)

1) We're no longer interested in -osr benchmarks as it's enabled by default
2) We need "tier0-instrumented" mode just to track improvements in instrumented Tier0 - our goal is to reduce overhead from it while keeping start-time the same in order to enable PGO by default, so basically these flags have to be set:
```
DOTNET_ReadyToRun=0
DOTNET_TieredPGO=1
DOTNET_TC_CallCounting=0
```
3) ARM64 seems to be dead on that page (doesn't use Ampere)

cc @AndyAyersMS @sebastienros

**Comment by sebastienros** [comment]
Here is the file to change for the updated modes: https://github.com/aspnet/Benchmarks/blob/main/build/pgo-scenarios.yml

I will remove the ARM64 option (PowerBI change). Do you need to get these running on Ampere (80), Linux|Windows?

**Comment by EgorBo** [comment]
> Here is the file to change for the updated modes: https://github.com/aspnet/Benchmarks/blob/main/build/pgo-scenarios.yml
> 
> I will remove the ARM64 option (PowerBI change). Do you need to get these running on Ampere (80), Linux|Windows?

Yes, we do need arm64 to test PGO 🙂
