### ISSUE TITLE
NativeAOT Stage1 benchmark should disable Tiered JIT for comparison

### ISSUE THREAD

**Issue by eerhardt** [aspnet/Benchmarks#1785]
When comparing NativeAOT to CoreCLR, it isn't an "apples-to-apples" comparison to compare the Tiered JIT to NativeAOT. Tiered JIT can use dynamic PGO to optimize the machine code more than NativeAOT can.

We should add a new configuration for non-Tiered JIT CoreCLR for comparison on the benchmarks. To get an "apples-to-apples" comparison with non-NativeAOT RPS.

cc @mangod9 @sebastienros @DamianEdwards @agocke @mitchdenny

**Comment by sebastienros** [comment]
But it's the default, I would assume that's a totally fair comparison. People will either compare CoreCLR with tiered jit or NativeAOT. 

Stupid counter arguments:
- Should we have a NativeAOT version that doesn't precompile the IL too because "apples-to-apples".
- If you remove a tire from a Ferrari it's not faster than a Kia

**Comment by sebastienros** [comment]
If it's to understand where the RPS difference is coming from and not for "fairness" then I understand better. That would help focus the work on where gains can be made.

**Comment by sebastienros** [comment]
Fixed by https://github.com/aspnet/Benchmarks/commit/ac93f4e19144cfb7e279a20030a38def7bd3a41a

**Comment by agocke** [comment]
The purpose of adding the config is so we can understand the breakdown and set the right goals. I agree that it makes sense in the real world to compare the default configurations, but we also believe that the native aot perf should basically match the static JIT perf, which is where our "5%" goal came from. If dynamic PGO ends up being 15% faster than static JIT, then I would expect the gap to aot to be the same. If it's not, that's definitely something I would want to know about
