### ISSUE TITLE
Benchmarks depends on Npgsql.EntityFrameworkCore.PostgreSQL (>= 6.0.8) but Npgsql.EntityFrameworkCore.PostgreSQL 6.0.8 was not found. An approximate best match of Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1 was resolved

### ISSUE THREAD

**Issue by mayadav1** [aspnet/Benchmarks#1808]
I am getting error while a running database.single_query benchmark with net6.0.
Used command :
crank --config "https://raw.githubusercontent.com/aspnet/Benchmarks/master/scenarios/database.benchmarks.yml" --config amd.benchmarks.yml --application.framework net6.0 --application.runtimeVersion 6.0.14 --application.collectCounters true --application.startTimeout '00:15:00' --profile genoa --scenario single_query --application.collect true --application.collectTimeout "00:15:00" --application.aspNetCoreVersion 6.0.14
Error message:
Command:
dotnet publish Benchmarks.csproj -c Release -o C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-32040\d0aq4mao.tg3\benchmarks\src\Benchmarks\published /p:MicrosoftNETCoreAppPackageVersion=6.0.14 /p:MicrosoftAspNetCoreAppPackageVersion=6.0.14 /p:GenerateErrorForMissingTargetingPacks=false /p:RestoreNoCache=true /p:MicrosoftWindowsDesktopAppPackageVersion=6.0.14 /p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App --framework net6.0 --self-contained -r win-x64
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-32040\d0aq4mao.tg3\benchmarks\src\Benchmarks\Benchmarks.csproj : warning NU1603: Benchmarks depends on Npgsql.EntityFrameworkCore.PostgreSQL (>= 6.0.8) but Npgsql.EntityFrameworkCore.PostgreSQL 6.0.8 was not found. An approximate best match of Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1 was resolved.
  Restored C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-32040\d0aq4mao.tg3\benchmarks\src\Benchmarks\Benchmarks.csproj (in 1.66 sec).
C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-32040\d0aq4mao.tg3\benchmarks\src\Benchmarks\Benchmarks.csproj : warning NU1603: Benchmarks depends on Npgsql.EntityFrameworkCore.PostgreSQL (>= 6.0.8) but Npgsql.EntityFrameworkCore.PostgreSQL 6.0.8 was not found. An approximate best match of Npgsql.EntityFrameworkCore.PostgreSQL 7.0.1 was resolved.
CSC : error CS1705: Assembly 'Npgsql.EntityFrameworkCore.PostgreSQL' with identity 'Npgsql.EntityFrameworkCore.PostgreSQL, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' uses 'Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' which has a higher version than referenced assembly 'Npgsql' with identity 'Npgsql, Version=6.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' [C:\Users\mayadav1\AppData\Local\Temp\2\benchmarks-agent\benchmarks-server-32040\d0aq4mao.tg3\benchmarks\src\Benchmarks\Benchmarks.csproj]
Exit code: 1

PS C:\Users\mayadav1\Desktop\netscripts> dotnet tool list -g
Package Id                      Version                  Commands
--------------------------------------------------------------------
microsoft.crank.agent           0.2.0-alpha.23156.1      crank-agent
microsoft.crank.controller      0.2.0-alpha.23156.1      crank

Your help will be appreciated.

**Comment by sebastienros** [comment]
@roji I think the npgsql package versions were changed recently. Some specific versions might not be available in internal feeds.

**Comment by sebastienros** [comment]
Asked for 6.0.8 to be added to the feeds.

**Comment by roji** [comment]
Sorry about that, yeah, I asked for the latest 8.0 previews but forgot to ask for the latest patches.

**Comment by sebastienros** [comment]
Tested locally and it works now
