### ISSUE TITLE
Add Composite Images to TE Scenarios

### ISSUE THREAD

**Issue by ivdiazsa** [aspnet/Benchmarks#1849]
Earlier this week (at the time of writing this issue), the composite images PR was merged to dotnet's docker repo. Now, the next step is to enable scenarios to be regularly run in [Tech Empower](https://msit.powerbi.com/groups/me/reports/10265790-7e2e-41d3-9388-86ab72be3fe9/ReportSectioneebab169a5994d194b69?experience=power-bi&clientSideAuth=0), alongside their counterparts, the normal ASP.NET images.

The main goal of adding these scenarios is to have a consistent way of comparing the performance of both versions, using different scenarios, in order to ensure no regressions occur, as well as fix those that do happen and identify other areas of improvement.

**Comment by ivdiazsa** [comment]
@sebastienros Here's a tracking issue for adding the composites to TE like we discussed. I don't have repo permissions so could you assign it to me? Thanks.

**Comment by ivdiazsa** [comment]
FYI @trylek

**Comment by sebastienros** [comment]
You need to join the team that is described on the main README

**Comment by ivdiazsa** [comment]
Closing as complete with PR #1854.
