### ISSUE TITLE
Benchmark pipelines failing (multiple causes)

### ISSUE THREAD

**Issue by mitchdenny** [aspnet/Benchmarks#1851]
Seeing a few different failures:

Example 1:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2190155&view=logs&j=5e20d31c-40e8-5c84-0a9d-b103be4eb1f2&t=80c4b7cf-ebf8-5dfe-1027-b239bd5fdc4a&l=23

>[STDERR] Unhandled exception. System.Net.Http.HttpRequestException: Error while copying content to a stream.

Example 2:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2190300&view=logs&j=e27ec99c-5535-546f-447d-949b0c4bf047&t=d03bf567-ab3e-5287-23d4-3e45792a666f&l=31

>[STDERR] Unhandled exception. System.TypeInitializationException: The type initializer for 'PlatformBenchmarks.BenchmarkApplication' threw an exception.
[STDERR]  ---> System.TypeInitializationException: The type initializer for 'RazorSlices.RazorSlice' threw an exception.

**Comment by sebastienros** [comment]
@DamianEdwards can you check if the commits last week may be the reason? I think all Platform benchmarks are broken since then. Am busy on a session/conference prep today and tomorrow. Thanks

**Comment by DamianEdwards** [comment]
OK I figured out what this is and oddly I thought it had been fixed the last time we hit this. It's caused by `RazorSlices` assembly scanning (boo) and failing when trying to load some assemblies in bin. It requires self-contained publish to reproduce. I'm updating RazorSlices to fix it now.
