### ISSUE TITLE
Container benchmarks for Alpine and Composite not working

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1904]
Example command line

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/containers.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario json_aspnet_alpine --profile intel-lin-app --profile intel-load-load --profile intel-db-db --variable rate=1000 --application.cpuLimitRatio 0.25 --application.memoryLimitInBytes 128000000 --load.job bombardier
```

Docker files:

https://github.com/aspnet/Benchmarks/blob/b6c14f48a317cf79bf864da4c6c59273845c658d/docker/container-matrix/Middleware-alpine.dockerfile

https://github.com/aspnet/Benchmarks/blob/b6c14f48a317cf79bf864da4c6c59273845c658d/docker/container-matrix/Middleware-composite.dockerfile

/cc @ivdiazsa

**Comment by ivdiazsa** [comment]
Just repro'd it and it seems things are getting screwed up again by versioning. Need to take a closer look at the Dockerfiles.

**Comment by ivdiazsa** [comment]
Closing as this is the issue that #1867 aims to fix in due time. Said due time came sooner than expected though.
