### ISSUE TITLE
Time To Frist Response regression on NativeAOT

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1908]
Windows and Linux

![image](https://github.com/aspnet/Benchmarks/assets/1165805/d99f0d34-b750-46ef-af86-8dc22580fa39)

Before:

```console
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario todosapipublishaot --profile intel-win-app --profile intel-lin-load --profile amd-lin2-db --application.packageReferences Microsoft.DotNet.ILCompiler=8.0.0-rc.2.23470.7 --application.aspNetCoreVersion 8.0.0-rtm.23470.10 --application.runtimeVersion 8.0.0-rc.2.23470.7 --application.sdkVersion 8.0.100-rtm.23470.21 --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net8.0 --application.options.collectCounters true
```

After:

```console
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/goldilocks.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/steadystate.profile.yml --scenario todosapipublishaot --profile intel-win-app --profile intel-lin-load --profile amd-lin2-db --application.packageReferences Microsoft.DotNet.ILCompiler=8.0.0-rc.2.23471.30 --application.aspNetCoreVersion 8.0.0-rtm.23471.8 --application.runtimeVersion 8.0.0-rc.2.23471.30 --application.sdkVersion 8.0.100-rtm.23471.13 --application.environmentVariables DOTNET_GCDynamicAdaptationMode=1 --application.framework net8.0 --application.options.collectCounters true
```

**Comment by sebastienros** [comment]
@MichalStrehovsky @eerhardt

**Comment by eerhardt** [comment]
The runtime diff:  https://github.com/dotnet/runtime/compare/49bf70a429a6122217f2c88e778ce8115ceac3bd...b1dbbb964a4daba07fe13c4150133f1d5d41ceb0

There were 2 other runtime builds in between those commits - "8.0.0-rc.2.23471.3" and "8.0.0-rc.2.23471.9". Trying to isolate this, it appears the regression came in between `8.0.0-rc.2.23470.7` and `8.0.0-rc.2.23471.3`. Here is the commit sha of each of the 4 builds:

8.0.0-rc.2.23470.7- 49bf70a429a6122217f2c88e778ce8115ceac3bd
8.0.0-rc.2.23471.3- 1757497f37245d1756870fb1c0b3221c0d235d54
8.0.0-rc.2.23471.9- 12fc9044307e32e143eb7cbaf1d68badf61b192c
8.0.0-rc.2.23471.30 - b1dbbb964a4daba07fe13c4150133f1d5d41ceb0

The diff between the builds that seem to cause the regression is: https://github.com/dotnet/runtime/compare/49bf70a429a6122217f2c88e778ce8115ceac3bd...1757497f37245d1756870fb1c0b3221c0d235d54

**Comment by MichalStrehovsky** [comment]
Given the full chart with the workstation GC mode looks like this (i.e. startup with workstation GC unaffected):

![image](https://github.com/aspnet/Benchmarks/assets/13110571/8deeb289-e045-4927-93bb-423036e3d6b9)

My bet is on the DATAS change in that commit range. Cc @Maoni0

Btw @sebastienros any plans to start measuring main? Looks like we also have a [size regression](https://github.com/dotnet/runtime/pull/93079#issuecomment-1751083795) in main already and being able to pinpoint a commit range would be helpful.

**Comment by sebastienros** [comment]
Was due to switch to anoother server.
