### ISSUE TITLE
WebSockets benchmarks failing

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1926]
Both on Linux and Windows

https://dev.azure.com/dnceng/internal/_build/results?buildId=2308615&view=logs&j=f3378e6d-2967-5b27-609f-e852aff53b11&t=c684bc60-b647-579c-a37c-36ec3aca46b3

**Comment by sebastienros** [comment]
/cc @BrennanConroy 

Could be a misconfiguration since I reorganized the targeted machines recently.

**Comment by BrennanConroy** [comment]
Ok, idk how to fix that then.

**Comment by sebastienros** [comment]
No worries, I'll take a look at some point

**Comment by BrennanConroy** [comment]
Done https://github.com/aspnet/Benchmarks/commit/a313a6c529928dcc1c9e77d72a576459aee8c473
