### ISSUE TITLE
Remove dependency on Microsoft.DotNet.Cli.Utils

### ISSUE THREAD

**Issue by mikeharder** [aspnet/benchmarks#194]
BenchmarksDriver is not a CLI tool, so it should not depend on Microsoft.DotNet.Cli.Utils.  Instead:

* Write output directly to Console
* Add dedicated `--verbose` flag rather than rely on `dotnet -d`

**Comment by dougbu** [comment]
Not sure I understand this issue. We use the driver from the command line and it's not clear what about `Microsoft.DotNet.Cli.Utils` is specific to tools. @mikeharder ?

**Comment by mikeharder** [comment]
I *think* `Microsoft.DotNet.Cli.Utils` is only intended to be used by an actual CLI tool, like `dotnet publish` where `publish` is the CLI tool.  `BenchmarksDriver` is not a CLI tool, it's just a console app.

Before this change, we were relying on the CLI to tell us whether the user wanted verbose output, which had a few downsides:
* It wasn't possible to get verbose output from BenchmarksDriver without also getting additional (unwanted) verbose output from the CLI itself.
* It wasn't possible to enable verbose output when using `dotnet BenchmarksDriver.dll` instead of `dotnet -d run`.

**Comment by dougbu** [comment]
:ok: I buy _those_ reasons 😺

**Comment by cesarbs** [comment]
Close?
