### ISSUE TITLE
Investigate serverframework 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/benchmarks#2]
http://www.serverframework.com

**Comment by benaadams** [comment]
Regitered RIO //build/ announce from 2011 
http://channel9.msdn.com/events/Build/BUILD2011/SAC-593T

**Comment by benaadams** [comment]
Having a ago at adding a RIO IOCP TcpServer

**Comment by davidfowl** [comment]
W00p sweet!

**Comment by benaadams** [comment]
Getting there, its a higher level of Interop crazy than I first expected...

**Comment by benaadams** [comment]
Moved the RIO to #9
