### ISSUE TITLE
SSLStream benchmarks failures

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#2009]
QUIC version issue. I assume the docker image needs to be updated.

https://dev.azure.com/dnceng/internal/_build/results?buildId=2505915&view=logs&j=9142df0d-7def-5570-e89d-e2d109dff91d&t=d67dfdfb-0bf3-56a1-52b2-f9f4f85a7eea

@CarnaViire

**Comment by CarnaViire** [comment]
@liveans or @rzikm, can you please update the version? the docker image is here: https://github.com/dotnet/crank/blob/main/docker/agent/Dockerfile

**Comment by rzikm** [comment]
This may be related to https://github.com/dotnet/runtime/issues/105788

**Comment by sebastienros** [comment]
They run in a Docker container because this makes it easier to maintain which tools/versions are installed, and also deploy crank updates. This may change in a near future.

If you run the linked Docker image locally you should be able to repro the same error. Host OS is Ubuntu 22.04 in our case.

**Comment by sebastienros** [comment]
Fixed in source package
