### ISSUE TITLE
Possible seconds/milliseconds confusion in TcpClient

### ISSUE THREAD

**Issue by rgesteve** [aspnet/Benchmarks#2016]
Two of the three uses of `Task.Delay` (using `int` as argument) pass a value seemingly meant to be in seconds, but [docs](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.delay?view=net-8.0#system-threading-tasks-task-delay(system-int32)) says the arg is interpreted to be in *milliseconds*.   Should these values be scaled by 1,000 at some point in the code? 

The occurrences I mean are:
* https://github.com/aspnet/Benchmarks/blob/main/src/TcpClient/Program.cs#L93
* https://github.com/aspnet/Benchmarks/blob/main/src/TcpClient/Program.cs#L99

Apologies if this is an error of my reading of the docs/comments.

**Comment by sebastienros** [comment]
You are correct. Either apply the factor, or better change the variables to be Timespans (calling it `Warmup` and `Duration`) and create the values correctly when initialized.
