### ISSUE TITLE
Automation for BenchmarkDotNet tests

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Benchmarks#208]
# Plan A
- [ ] New project BenchmarkDotNetServer
  - Input: (repo@branch, path to BenchmarkDotNet test project)
  - Computation: Clone, restore, build, run, parse output
  - Output: Set of tests with performance data for each. Optionally write to SQL.
- [ ] New project BenchmarkDotNetDriver
- [ ] Refactor existing automation to reuse common code

# Plan B
- [ ] Use a TeamCity Agent on a dedicated machine to build, run the tests, and upload results to SQL

# Common
- [ ] New Power BI dashboard to visualize data in SQL
- [ ] New server to run tests without impacting existing TechEmpower automation

**Comment by adamsitnik** [comment]
please let me know if you need any help with BenchmarkDotNet
