### ISSUE TITLE
Profile a basic WebListener scenario

### ISSUE THREAD

**Issue by Eilon** [aspnet/benchmarks#21]

**Comment by DamianEdwards** [comment]
We should add numbers for WebListener for all the scenarios. The server can be passed in at execution time on the command line or set with a hosting.json file so it's already pluggable (yay ASP.NET Core!).

**Comment by dougbu** [comment]
Is this yet-another dupe of #112?

**Comment by mikeharder** [comment]
@dougbu: yep
