### ISSUE TITLE
[Question] MVC benchmark results

### ISSUE THREAD

**Issue by dazinator** [aspnet/benchmarks#221]
Hello,
Do you have the benchmark results published for the tests that utilise MVC?

**Comment by mikeharder** [comment]
You can use the official TechEmpower results for Round 13:

https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=plaintext

Search for "aspnetcore-mvc".

**Comment by M-Yankov** [comment]
> https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=plaintext
> Search for "aspnetcore-mvc".

@mikeharder on the link above I coudn't find `aspnetcore-mvc` . Any idea?

**Comment by benaadams** [comment]
Was renamed to `aspcore-mvc` 

https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=plaintext&p=zik0zj-zik0zj-zijocf-5m9r

**Comment by M-Yankov** [comment]
Thanks, that was the statistics that i was looking for.
