### ISSUE TITLE
Benchmark DotNetty

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Benchmarks#222]
Run benchmarks against https://github.com/Azure/DotNetty

**Comment by davidfowl** [comment]
How? Theres no http transport...

**Comment by mikeharder** [comment]
@DamianEdwards asked if we had benchmarked DotNetty so I filed this issue.  I didn't look into any details.

**Comment by davidfowl** [comment]
Ah

**Comment by davidfowl** [comment]
@nayato Are you guys working on porting the http transport?
