### ISSUE TITLE
Add PHP benchmarks with Peachpie

### ISSUE THREAD

**Issue by benaadams** [aspnet/benchmarks#223]
| Lng | Plt | FE      |
|-----|-----|---------|
| PHP | Net | Kestrel |

http://www.peachpie.io/2017/02/wordpress-announcement.html

https://github.com/benaadams/PeachpieBenchmarks (plaintext)

Example php: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/php

**Comment by davidfowl** [comment]
I don't think this should be part of our benchmarks. It should be in techempower though.

**Comment by benaadams** [comment]
I do mean more submit; rather than track - as the setup is mostly the same (e.g. download install dotnet etc)

Perhaps an alt-benchmark repo?

**Comment by benaadams** [comment]
Also will need to take changes to install scripts from here (as project systems evolve and .NET and ASP.NET versions increase)
