### ISSUE TITLE
Why don't you use .NET code to benchmark .NET server

### ISSUE THREAD

**Issue by abdullin** [aspnet/Benchmarks#226]
Just curious, why don't you use .NET code (e.g. HttpClient) to benchmark ASP.NET Core? 

That would provide a more meaningful real-world benchmark scenario, since quite often .NET APIs are created in companies that are heavily invested in Microsoft technologies and hence have .NET clients as well.

**Comment by cesarbs** [comment]
We use the same benchmarking methodology as TechEmpower, which uses wrk in their benchmarks. Search for 'wrk' here: https://www.techempower.com/benchmarks/#section=motivation&hw=ph&test=plaintext

**Comment by shravan2x** [comment]
@cesarbs I'm interested in knowing the answer to this too. In the absence of @mikeharder's and @stephentoub's comments, could you point me somewhere where I could follow up on the `HttpClient` news?
