### ISSUE TITLE
Something up with EF update?

### ISSUE THREAD

**Issue by benaadams** [aspnet/Benchmarks#234]
https://www.techempower.com/benchmarks/previews/round14/r13-vs-r14p1.html

Down -16.4% for round 14 (preview) and seems incongruous with the other aspnetcore update scenarios

**Comment by ajcvickers** [comment]
@anpete Can you take a look at this?
/cc @divega

**Comment by mikeharder** [comment]
The main change between Rounds 13 and 14 was upgrading ASP.NET Core and .NET Core from 1.0 to 1.1:

https://github.com/TechEmpower/FrameworkBenchmarks/commit/399a99a724647eee42ddd3c3a54e31be3fbbaac2

Npgsql was also changed from floating "3.2.0-*" to pinned "3.2.0-beta1" (https://github.com/TechEmpower/FrameworkBenchmarks/commit/5e0887dff4fa5b572956cd709c0475aa9e464767), but this shouldn't have impacted performance.

As a next step I would try to reproduce these results using 1.0 and 1.1 on our own hardware.
