### ISSUE TITLE
Update benchmarks to use versions in dependencies.props

### ISSUE THREAD

**Issue by davidfowl** [aspnet/benchmarks#251]
Today the projects in benchmarks have a dependencies.props but we still hard code versions in the project files themselves.

https://github.com/aspnet/benchmarks/blob/ae6af537186f8493d34f8ac97f77d6b878aa573b/src/Benchmarks/Benchmarks.csproj#L11-L32

We should replace these with properties specified in `dependencies.props`

**Comment by dougbu** [comment]
Taking this as I'm doing related cleanup / alignment w/ TechEmpower repo.

**Comment by davidfowl** [comment]
👍

**Comment by dougbu** [comment]
8fa6759
