### ISSUE TITLE
Upgrade Npgsql from "3.2.0-*" to "3.*"

### ISSUE THREAD

**Issue by mikeharder** [aspnet/benchmarks#263]
Now that `Npgsql 3.2.0` has shipped, the dependency version should be changed from `3.2.0-*` to `3.*`.  We only needed `3.2.0-*` to pickup `3.2.0-beta`, since `3.*` doesn't match pre-release versions.

**Comment by dougbu** [comment]
Taking this as I'm doing related cleanup / alignment w/ TechEmpower repo.

**Comment by dougbu** [comment]
8fa6759
