### ISSUE TITLE
Nodejs v8.0.0 comparsion

### ISSUE THREAD

**Issue by dcworldwide** [aspnet/benchmarks#267]
Would it be possible to have the benchmark compare the newly released Nodejs v8.0.0 running V8 5.8?

**Comment by mikeharder** [comment]
If you're asking about the data at https://github.com/aspnet/benchmarks/blob/dev/README.md, it is out of date.  The best place to compare performance of ASP.NET Core with other frameworks is https://www.techempower.com/benchmarks/.
