### ISSUE TITLE
Does Node tests use Cluster?

### ISSUE THREAD

**Issue by brunolm** [aspnet/benchmarks#279]
Cluster in Node https://nodejs.org/api/cluster.html makes the application start in multiple threads, making performance significantly better.

I wonder if this project has a comparison of .NET Core with Node + Clusters

**Comment by simonmurdock** [comment]
I think they are using the Tech Empower node JS app,

**Comment by brunolm** [comment]
So I think that is a yes... :)

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/app.js
