### ISSUE TITLE
Update Dapper & Postgres driver packages

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/benchmarks#305]
The following packages are out of date. We should update them and take measurements that compare before and after.

- Dapper in use is 1.0.0, current version is 1.50.2
- Npgsql in use is 3.0.0, current version is 3.2.5
- Npgsql.EntityFrameworkCore.PostgreSQL in use is 2.0.0--, current version is 2.0.0

**Comment by mikeharder** [comment]
Please also update the versions at https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnetcore/Benchmarks.

**Comment by sebastienros** [comment]
It has already be done by @dougbu on Jun 6, for both repos.
