### ISSUE TITLE
Benchmark static file server

### ISSUE THREAD

**Issue by davidfowl** [aspnet/benchmarks#32]
/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
:+1:

**Comment by DamianEdwards** [comment]
There are [static files of various sizes](https://github.com/aspnet/benchmarks/tree/dev/src/Benchmarks/wwwroot) in the project now and the middleware is enabled via a scenario, so we just need to do some runs and record results.

Probably want to do runs for the following connection counts for all the file sizes:
- 8
- 16
- 32
- 64
- 128
- 256

**Comment by dougbu** [comment]
These scenarios exist. But, we aren't running / measuring these scenarios regularly and aren't measuring impact of adding StaticFiles (when no file matches) against PlainText or JSON scenario without the middleware. Will use this issue to cover completion of that work.

**Comment by dougbu** [comment]
52570f7
