### ISSUE TITLE
Investigate performance of "Enforce Max Auto Prepare for PostgreSQL EF/Dapper"

### ISSUE THREAD

**Issue by mikeharder** [aspnet/benchmarks#341]
The change in https://github.com/aspnet/benchmarks/pull/302 and https://github.com/aspnet/FrameworkBenchmarks/pull/5 was intended to improve performance.  However, when I tested this change the results were mixed:

Scenario|RPS (no auto prepare)|RPS (max auto prepare = 20)|Relative
-----|-----|-----|-----
FortunesRaw|16,439|19536|119%
FortunesDapper|15,555|9703|62%
FortunesEf|10,655|7656|72%
 | | | 
MultiUpdateRaw|783|891|114%
MultiUpdateDapper|652|736|113%
MultiUpdateEf|17|176|1035%

Conclusions:

1.	The increase in MultiUpdateDapper and MultiUpdateEf match expectations, with a huge improvement in EF.
2.	The decrease in FortunesDapper and FortunesEf is significant and unexpected.
3.	The increase in FortunesRaw and MultiUpdateRaw is also unexpected, since we already call Prepare(): https://github.com/aspnet/benchmarks/blob/8fa6759ea7ab145640a65b5739b8e6dd3df76bfd/src/Benchmarks/Data/RawDb.cs#L68

We will not be able to merge this PR until we address the decrease in (2), and understand the increase in (3).

**Comment by sebastienros** [comment]
Auto prepared applied on connection string after `Prepare()` call was removed. Perf and stability improved on all scenarios.
