### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by lillo42** [aspnet/benchmarks#347]
Hi,
I would like to know when README.md will be update?

**Comment by mikeharder** [comment]
What information are you looking for?

**Comment by lillo42** [comment]
I am looking for Req/sec,
I would like to know how is AspNET Core performance.

**Comment by mikeharder** [comment]
The best sources of current performance data are:

* [Official TechEmpower Benchmarks](https://www.techempower.com/benchmarks)
* [ASP.NET Benchmarks (run after every build)](https://aka.ms/aspnet/benchmarks)
