### ISSUE TITLE
Add a benchmark test for Jil as Json serializer

### ISSUE THREAD

**Issue by benaadams** [aspnet/Benchmarks#35]
https://www.nuget.org/packages/Jil/2.13.0-beta1

/cc @NickCraver @mgravell @kevin-montrose

**Comment by NickCraver** [comment]
Taking a peek now. Sorry, we've been really busy here on perf of something launching to a much higher load soon - hoping to get back to Kestrel next week-ish.

**Comment by NickCraver** [comment]
PR is in, #36 is awaiting!

**Comment by DamianEdwards** [comment]
Let's get this PR in and the results recorded.
