### ISSUE TITLE
System.InvalidOperationException: 'Transport must be specified'

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/benchmarks#366]
![image](https://user-images.githubusercontent.com/1798510/35243092-fea0a5b6-ffbb-11e7-9311-6b6a83b36187.png)

**Comment by MaherJendoubi** [comment]
dotnet --version = 2.2.0-preview1-008003

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/35243265-862e55d2-ffbc-11e7-897e-64128639c3be.png)

**Comment by sebastienros** [comment]
When you start the application it requires `--kestrelTransport Libuv` or `--kestrelTransport Sockets`.

**Comment by MaherJendoubi** [comment]
Thanks a lot! @sebastienros
