### ISSUE TITLE
Where to see the benchmarking results?

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/benchmarks#367]
![image](https://user-images.githubusercontent.com/1798510/35247973-9e2434ee-ffcc-11e7-8031-f3f6a558418c.png)

**Comment by MaherJendoubi** [comment]
@sebastienros I run dotnet run --configuration Release --kestrelTransport Libuv
then I chose Plaintext but I can not see the result of benchmarks...

**Comment by BrennanConroy** [comment]
Thats because all you've done so far is run the server. You now need to actually run work against it.
Check out the [Readme](https://github.com/aspnet/benchmarks#generating-load) where we talk about creating work.

**Comment by sebastienros** [comment]
https://aka.ms/aspnet/benchmarks
