### ISSUE TITLE
Use optimized content type for MVC actions

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#381]
TE warning in the build log

```
     Content encoding found in "application/json; charset=utf-8" where "application/json" is acceptable.
     Additional response bytes may negatively affect benchmark performance.
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

All these MVC actions use `[Produces("application/json")]`. Maybe we can use a better way to set the content type to improve it.

https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/342443158

**Comment by sebastienros** [comment]
@davidfowl any idea? Otherwise I will investigate

**Comment by benaadams** [comment]
`System.Net.Http.StringContent` always setting encoding whether you want it or not?
 https://github.com/dotnet/corefx/issues/25290

[System/Net/Http/StringContent.cs#L26-L34](https://github.com/dotnet/corefx/blob/cac1f05d705072c4bb20045f84ef3370d87a976a/src/System.Net.Http/src/System/Net/Http/StringContent.cs#L26-L34)
```csharp
headerValue.CharSet = (encoding == null) ? HttpContent.DefaultStringEncoding.WebName : encoding.WebName;

Headers.ContentType = headerValue;
```

**Comment by DamianEdwards** [comment]
Any idea if this is still something we should look into?

**Comment by sebastienros** [comment]
I don't think it matters, it's for MVC which is lower in the results, and this would only impact networking which wouldn't improve the results.
