### ISSUE TITLE
TcpClient missing in dotnet5.4 but in dotnet5.5 for "System.Net.Sockets" based on required announcement

### ISSUE THREAD

**Issue by zhangxin511** [aspnet/benchmarks#40]
@Eilon @Tratcher 
I am not sure where to put my original issue so I just leave it here.

My original issue is: https://github.com/aspnet/Announcements/issues/133
@Eilon I am recently update the target framework from dnxcore50 to dotnet5.4 based on your annoucement "Switching to new ‘dotnet’ target framework monikers", when we are updating to rc1-final/update1

One of our class library using TcpClient in System.Net.Sockets. When I update to dotnet5.4, it won't build because it cannot find TcpClient. After change our project.json from dotnet5.4 to dotnet5.5 it working fine. So what is the best practice for this? Should I change my project.json to dotnet5.5 and change #if DNXCORE50 to #if DOTNET5_5 for ALL my other library?

It seems on nuget.org only System.Net.Sockets support 5.4 and 5.5, all other packages only support dotnet5.4, what is the compatibility here?

**Comment by Tratcher** [comment]
Yes, class libraries should use dotnet5.x, Use the lowest version that has what you need in it (e.g. 5.5 in this case). Only applications (e.g. a project with a Main entry point) should have dnx or dnxcore targets.

**Comment by zhangxin511** [comment]
Thank you @Tratcher for the quick response!
