### ISSUE TITLE
Benchmark standalone routing performance

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Benchmarks#41]

**Comment by simonmurdock** [comment]
I was thinking about this earlier today. Would be very cool to see!

**Comment by DamianEdwards** [comment]
@davidfowl are you suggesting just adding plaintext and json routing scenarios? Or a more complex routing-specific scenario with many patterns, matches, constraints, etc.?

**Comment by davidfowl** [comment]
@DamianEdwards it would be interesting to see what our performance drops to if we changed our if statements in the benchmarks repo to use routing.

**Comment by rynowak** [comment]
I didn't say there wasn't a bug, I see we should assign the bugs and start working on them :trollface:
