### ISSUE TITLE
Refactor repeating dereference calls in MVC plaintext

### ISSUE THREAD

**Issue by jo-ninja** [aspnet/benchmarks#425]
There are repeating dereference calls in MVC plaintext code: 

```csharp
context.HttpContext.Response.StatusCode = StatusCodes.Status200OK;
context.HttpContext.Response.ContentType = "text/plain";
context.HttpContext.Response.ContentLength = _helloWorldPayload.Length;
return context.HttpContext.Response.Body.WriteAsync(_helloWorldPayload, 0, _helloWorldPayload.Length);
```

Usually by eliminating the repeating calls should make it run a little bit faster (not a magnitude, however):
- `context.HttpContext.Response`
- `_helloWorldPayload.Length`

Refer to my investigation result: https://github.com/aspnet/benchmarks/pull/417#issuecomment-374001568

/cc @DamianEdwards @benaadams any thoughts?

**Comment by benaadams** [comment]
Removing the calls is a similar pattern to plaintext

https://github.com/aspnet/benchmarks/blob/43582d9a88d8c9e0e919ff7b7bc61f922fae017e/src/Benchmarks/Middleware/PlaintextMiddleware.cs#L35-L42
