### ISSUE TITLE
Benchmarks should set ASPNETCORE_URLS

### ISSUE THREAD

**Issue by davidfowl** [aspnet/benchmarks#449]
The WebHostBuilder picks that up automatically which means applications don't need to manually handle parsing the port from command line arguments.

**Comment by sebastienros** [comment]
It already sets it, but the application has been changed to prefer command line, which is also set when starting the app ... I might remove that from the command line. And then we can override it again from the diver command line

**Comment by davidfowl** [comment]
Oh it does?

**Comment by davidfowl** [comment]
Closing
