### ISSUE TITLE
Json benchmark, use struct rather than class?

### ISSUE THREAD

**Issue by benaadams** [aspnet/benchmarks#478]
The Json benchmark for both Platform and mainline is using a anonymous type for the message. 

This gets converted into a sealed class.

What would be the difference if a defined `struct` rather than was used instead of a `class` e.g.

```csharp
readonly struct Message
{
    public readonly string message;
  
    public Message(string message)
    {
        this.message = message;
    }
}
```
and
```csharp
using (var sw = new StreamWriter(httpContext.Response.Body, _encoding, bufferSize: _bufferSize))
{
    _json.Serialize(sw, new { message = "Hello, World!" });
}
```
to
```csharp
using (var sw = new StreamWriter(httpContext.Response.Body, _encoding, bufferSize: _bufferSize))
{
    _json.Serialize(sw, new Message("Hello, World!"));
}
```

/cc @JamesNK @davidfowl @sebastienros

**Comment by JamesNK** [comment]
It will be boxed

**Comment by benaadams** [comment]
> It will be boxed

😢

**Comment by benaadams** [comment]
Still should work for the Platform which looks like it has a generic path in Utf8Json https://github.com/TechEmpower/FrameworkBenchmarks/compare/master...benaadams:struct-platformjson?expand=1
