### ISSUE TITLE
Add a -diff flag for testing performance changes compared to the baseline

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Benchmarks#518]
The typical workflow for a performance change is to do the following:
- Make a branch
- Make the change
- Pick a scenario you think should be improved by the change
- Run the scenario 3 times without your change (to reduce the variance and get a decent number)
- Run the scenario 3 times with your change

It would be great if there was a single command you could run that meant to do the above steps and produce a single output with the a table of the before after and the % diff between the baseline (what's currently there) and your changes.

```
dotnet run -c release --server "{server}" --client "{client}" -n {scenario} -j "{scenario-file.json}" --outputFile "{file-with-changes.dll}" --no-warmup -md -diff
```

cc @sebastienros

**Comment by sebastienros** [comment]
1- The diff could be based on outputfile, but it could also be on different aspnet/runtime version, different scenarios, ... So I am not sure a single command and a `-ddiff` flag would be able to handle these differences.
2- We usually run the baseline once, then try changes multiple times. I don't think it should run the baseline everytime.

My suggestion:
Add a flag to store the results in a file, and give a friendly name like "baseline". e.g., --save baseline
Add a flag to compare the results to a previous run (the baseline) and output the results in a diff format e.g, --diff baseline

It would still be compatible with the `-i` argument that can run the same thing multiple times and use the average.

**Comment by davidfowl** [comment]
I'd prefer a single command instead of running many. There's some error proneness doing things today. Ideally the single command can do what you suggest behind the scenes since the intermediate results aren't super interesting.

**Comment by sebastienros** [comment]
It can't be a single command without breaking everything. How do you know what are the parameters for the baselines and for the new measure? `--outputfile` is only one way to vary a benchmark. There are many more options, or combinations of options.

BTW here is what I am getting right now with that implemented.

```
| Description |    RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | First Request (ms) | Latency (ms) | Ratio |
| ----------- | ------ | ------- | ----------- | ----------------- | ------------ | ------------------ | ------------ | ----- |
|    Baseline | 54,220 |      82 |         338 |               5.1 |          168 |              142.9 |          1.3 |  1.00 |
|    16 bytes | 53,743 |      84 |         338 |               5.1 |          173 |              128.5 |          1.4 |  0.99 |
```
