### ISSUE TITLE
Performance regression: JsonPlatform

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#521]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| JsonPlatform | Windows, http, KestrelSockets | 2018-10-05 10:13:45Z | 527577 | 505388 | -4.21 % | -3.12 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-preview3-35393__
Microsoft.NetCore.App __2.2.0-preview3-27001-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-preview3-35406__
Microsoft.NetCore.App __2.2.0-preview3-27001-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/Universe/compare/628a3821bdffb56d1f16d116d80ffac3debfd42e...a59c61a976a713990953961fe163576e392584b4

**Comment by sebastienros** [comment]
Local slow down that recovered afterwards
