### ISSUE TITLE
Performance regression: MvcDbMultiUpdateDapper, DbMultiUpdateDapper

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#526]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiUpdateDapper | Linux, http, KestrelSockets | 2018-10-10 20:52:11Z | 1619 | 1526 | -5.74 % | -3.08 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-preview3-35438__
Microsoft.NetCore.App __2.2.0-preview3-27008-03__

After versions:
Microsoft.AspNetCore.App __2.2.0-preview3-35451__
Microsoft.NetCore.App __2.2.0-preview3-27008-03__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/Universe/compare/21b98de09ba76f106c2d13480de9107d7444d999...8fbaccaa9e9d4d44c697bc02a137582063840855

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcDbMultiUpdateDapper | Linux, http, KestrelSockets | 2018-10-10 20:55:04Z | 1622 | 1520 | -6.29 % | -2.98 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-preview3-35438__
Microsoft.NetCore.App __2.2.0-preview3-27008-03__

After versions:
Microsoft.AspNetCore.App __2.2.0-preview3-35451__
Microsoft.NetCore.App __2.2.0-preview3-27008-03__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/Universe/compare/21b98de09ba76f106c2d13480de9107d7444d999...8fbaccaa9e9d4d44c697bc02a137582063840855

**Comment by sebastienros** [comment]
Recovered
