### ISSUE TITLE
Azure VM benchmark

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Benchmarks#55]
Maybe it's a good idea to put the benchmark in azure VM

My laptop (local)
![image](https://cloud.githubusercontent.com/assets/12871379/13177858/04354c90-d71c-11e5-86b6-d66cc6d788e1.png)

Azure machine A0
![image](https://cloud.githubusercontent.com/assets/12871379/13177873/1801acfa-d71c-11e5-9776-e736a6a10559.png)

42ms to 8.82s :(

**Comment by benaadams** [comment]
I've often be told you shouldn't run benchmarking on A0 machines as they aren't a guaranteed dedicated CPU, but shared CPU which depends on other workloads on the machine; so can't be used to extrapolate scale-up.

What happens if you go A1+? Also is that the first "warm-up" request that starts the application?

**Comment by andrew-vandenbrink** [comment]
I'm not trying to do any benchmark, just testing my application

I'll try to get A1+ machine once I have the free azure credit

It's not first warm up run for sure

![image](https://cloud.githubusercontent.com/assets/12871379/13178553/ba8c3942-d71f-11e5-99a1-279eda084f20.png)
On the most left you see the dnx compiling everything

What I'm trying to get is how good the performance if you run it on low level machine? 
A minimum azure vm level to get to have acceptable performance, casual performance like blog or news site with xxx numbers of visitors

**Comment by andrew-vandenbrink** [comment]
What im trying to say is its good to have awesome  performance in shiny gold plated machine, but how it is on this poor man machine?

**Comment by SajayAntony** [comment]
The TechEmpower Round 11 does have runs on [EC2](https://www.techempower.com/benchmarks/#section=data-r11&hw=ec2&test=plaintext). It does makes sense to consider getting numbers on Azure at some point provided we are aware that there is potential for high variability and low confidence numbers. This would enable us to understand a ballpark figure when running in the cloud for starts but for product engineering we want to stay close to monitoring on physical hardware with least noise possible to track regressions. This means low power variations and isolated dedicated networks as well.

**Comment by davidfowl** [comment]
> On the most left you see the dnx compiling everything

@andrew-vandenbrink you should publish a precompiled application if you want the best performance. Also make sure you're in release mode and not debug mode.

**Comment by andrew-vandenbrink** [comment]
@davidfowl I did publish to file system in release mode from visual studio then upload it manually to my vm in azure.

As the publish contains lot of source code, I thought the dnx will compile it on first time run. Otherwise not quite sure why dnx using my cpu.

What I also notice is the performance is much faster in the weekend.

**Comment by benaadams** [comment]
@andrew-vandenbrink I use

`dnu publish --no-source --include-symbols --configuration Release --runtime active`

usually also with `-o I:\location` to get it to move to root with shorter path lengths

**Comment by andrew-vandenbrink** [comment]
@benaadams I don't use --no-source due the fact that I use asp.net core so I change things while the web is running  but I can assure you I use release mode.

![image](https://cloud.githubusercontent.com/assets/12871379/13277643/be72afec-daca-11e5-8c06-81c5ee209234.png)

![image](https://cloud.githubusercontent.com/assets/12871379/13277391/d5f9db24-dac8-11e5-8a84-98a99bcb61ee.png)

I don't change anything and it is faster now.
It could be **azure noisy neighbor**.

![image](https://cloud.githubusercontent.com/assets/12871379/13277534/e37c302a-dac9-11e5-86df-4a9b2a879f17.png)
No one else access my web site but me, I don't deploy anything today. That means dnx take 50% of my cpu doing something for the first request after no one accessing it.
