### ISSUE TITLE
Performance regression: PlaintextNonPipelined, Json, JsonPlatform, HttpClientFactory, HttpClientParallel ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#561]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| HttpClient | Windows, http, KestrelSockets | 2018-11-06 03:52:41Z | 100463 | 86681 | -13.72 % | -16.49 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35634__
Microsoft.NetCore.App __2.2.0-rtm-27023-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35637__
Microsoft.NetCore.App __2.2.0-rtm-27105-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/f3809a8b97a0aa3be762b991e3aab629bdd8f77b...90b11de8f1838e3ec3a0b963eceeea6ebe54b857

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/7bcae0e6fc02da4d3bca6fba557bc5aae691827a...694e15f9974011662b3d5d17b2e3c248b33b527e

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/614fe941f6af28dc1217b6c474cc1ef0eab74c5f...47e6ebe80bb5946a49f974ed73b223e332655f36

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| HttpClientFactory | Windows, http, KestrelSockets | 2018-11-06 03:54:56Z | 94971 | 82285 | -13.36 % | -3.44 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35634__
Microsoft.NetCore.App __2.2.0-rtm-27023-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35637__
Microsoft.NetCore.App __2.2.0-rtm-27105-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/f3809a8b97a0aa3be762b991e3aab629bdd8f77b...90b11de8f1838e3ec3a0b963eceeea6ebe54b857

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/7bcae0e6fc02da4d3bca6fba557bc5aae691827a...694e15f9974011662b3d5d17b2e3c248b33b527e

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/614fe941f6af28dc1217b6c474cc1ef0eab74c5f...47e6ebe80bb5946a49f974ed73b223e332655f36

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| HttpClientParallel | Windows, http, KestrelSockets | 2018-11-06 03:53:46Z | 18184 | 15051 | -17.23 % | -21.05 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35634__
Microsoft.NetCore.App __2.2.0-rtm-27023-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35637__
Microsoft.NetCore.App __2.2.0-rtm-27105-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/f3809a8b97a0aa3be762b991e3aab629bdd8f77b...90b11de8f1838e3ec3a0b963eceeea6ebe54b857

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/7bcae0e6fc02da4d3bca6fba557bc5aae691827a...694e15f9974011662b3d5d17b2e3c248b33b527e

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/614fe941f6af28dc1217b6c474cc1ef0eab74c5f...47e6ebe80bb5946a49f974ed73b223e332655f36

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, https, KestrelSockets | 2018-11-06 04:23:48Z | 207404 | 202659 | -2.29 % | -2.39 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35634__
Microsoft.NetCore.App __2.2.0-rtm-27023-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35637__
Microsoft.NetCore.App __2.2.0-rtm-27105-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/f3809a8b97a0aa3be762b991e3aab629bdd8f77b...90b11de8f1838e3ec3a0b963eceeea6ebe54b857

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/7bcae0e6fc02da4d3bca6fba557bc5aae691827a...694e15f9974011662b3d5d17b2e3c248b33b527e

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/614fe941f6af28dc1217b6c474cc1ef0eab74c5f...47e6ebe80bb5946a49f974ed73b223e332655f36

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| JsonPlatform | Linux, http, KestrelSockets | 2018-11-06 04:10:48Z | 536882 | 522384 | -2.7 % | -2.14 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35634__
Microsoft.NetCore.App __2.2.0-rtm-27023-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35637__
Microsoft.NetCore.App __2.2.0-rtm-27105-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/f3809a8b97a0aa3be762b991e3aab629bdd8f77b...90b11de8f1838e3ec3a0b963eceeea6ebe54b857

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/7bcae0e6fc02da4d3bca6fba557bc5aae691827a...694e15f9974011662b3d5d17b2e3c248b33b527e

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/614fe941f6af28dc1217b6c474cc1ef0eab74c5f...47e6ebe80bb5946a49f974ed73b223e332655f36

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| PlaintextNonPipelined | Linux, https, KestrelSockets | 2018-11-06 04:26:09Z | 234257 | 220555 | -5.85 % | -6.43 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35634__
Microsoft.NetCore.App __2.2.0-rtm-27023-02__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35637__
Microsoft.NetCore.App __2.2.0-rtm-27105-02__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/f3809a8b97a0aa3be762b991e3aab629bdd8f77b...90b11de8f1838e3ec3a0b963eceeea6ebe54b857

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/7bcae0e6fc02da4d3bca6fba557bc5aae691827a...694e15f9974011662b3d5d17b2e3c248b33b527e

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/614fe941f6af28dc1217b6c474cc1ef0eab74c5f...47e6ebe80bb5946a49f974ed73b223e332655f36

**Comment by sebastienros** [comment]
/cc @davidsh @stephentoub

The regression in HttpClient scenarios seems to be related to a recent commit related to auth schema casing. I will try to isolate this change on a custom build and repeat the benchmark tomorrow.

https://github.com/dotnet/corefx/compare/7bcae0e6fc02da4d3bca6fba557bc5aae691827a...694e15f9974011662b3d5d17b2e3c248b33b527e

**Comment by sebastienros** [comment]
Note it also includes Tiered Compilation off by default, so I can't guaranty this is related to HttpClient changes only. Currently running the numbers.

**Comment by sebastienros** [comment]
@davidsh @stephentoub Please disregard, this regression is only due to Tiered Compilation being turned off by default now.

**Comment by stephentoub** [comment]
Thanks, that makes more sense :)
