### ISSUE TITLE
Performance regression: DbMultiUpdateRaw

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#572]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| DbMultiUpdateRaw | Linux, http, KestrelSockets | 2018-11-10 12:46:11Z | 3635 | 3485 | -4.13 % | -2.23 σ |

Before versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35676__
Microsoft.NetCore.App __2.2.0-rtm-27109-04__

After versions:
Microsoft.AspNetCore.App __2.2.0-rtm-35677__
Microsoft.NetCore.App __2.2.0-rtm-27109-04__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/7060d3a6c56ca835f7e7435e2d12a765e5293ac7...f64d6a2b501047af3ac9d76f221909700b95337d

**Comment by sebastienros** [comment]
False positive
