### ISSUE TITLE
Performance regression: ResponseCachingPlaintextVaryByCached

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#599]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| ResponseCachingPlaintextVaryByCached | Linux, http, KestrelSockets | 2019-01-11 08:29:04Z | 1356008 | 1222009 | -9.88 % | -3 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19060-0314__
Microsoft.NetCore.App __3.0.0-preview-27219-3__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview-19060-0318__
Microsoft.NetCore.App __3.0.0-preview-27219-3__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/5887e412c667f1ad7f1e14d6386ff4ef2b3fb533...5299eff6160d8f9c86299f80430cedf0fbe52ff5

**Comment by sebastienros** [comment]
FP
