### ISSUE TITLE
Implement Netty plaintext implemenation for comparison

### ISSUE THREAD

**Issue by SajayAntony** [aspnet/benchmarks#61]

**Comment by SajayAntony** [comment]
Closing this since we will be using the TechEmpower implementation - 
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/netty
cc @nathana1

**Comment by Sdzeng** [comment]
I'm download the source code and try to bulid.But I found it has an error:
    "Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-*"

 not found.

Has anyone successfully  built this repro? If so could you point me to a guide or explain the process?

**Comment by SajayAntony** [comment]
Hi @Sdzeng - would recommend opening another issue to track the build failures.
