### ISSUE TITLE
Show MySQL results in Power BI dashboard

### ISSUE THREAD

**Issue by bgrainger** [aspnet/Benchmarks#615]
AFAIK, the "DbFortunesRaw", "EF Fortunes", etc. benchmarks in the [Power BI dashboard](https://aka.ms/aspnet/benchmarks) are all PostgreSQL + npgsql.

While MySQL performance isn't as good as PostgreSQL (in absolute numbers), MySqlConnector is competitive against other frameworks' MySQL support (in TechEmpower Benchmarks) and it would be useful to track its trends over time.

I don't want to clutter up the primary dashboards too much, but it would be very nice to have some graphs publicly available. CC @sebastienros

**Comment by sebastienros** [comment]
I have already opened the discussion internally to allow other frameworks to be benchmarked and displayed on custom dashboards. Think about ImageSharp, Dapper, JSON.NET ... any library that is used a lot among .NET devs where any benefit would have a tremendous impact.

I also talked about opening the infrastructure publicly to some approved contributors that would use it to work on perf (you, @benaadams, ...)

I didn't get any push back, now we need to find the budget to setup some machines. But also some time to balance all the current work I have to do with this new task, which is not a priority right now.

**Comment by roji** [comment]
Even before opening the infrastructure publicly, it could make sense to simply have the existing data benchmarks with other platforms, no? I'm not sure how it would fit into the existing dashboards exactly, but it would be useful to have them there...

**Comment by DamianEdwards** [comment]
Closing this out due to age. Feel free to open a new issue if required.
