### ISSUE TITLE
Add event annotations to timeline

### ISSUE THREAD

**Issue by roji** [aspnet/Benchmarks#616]
Not sure if PowerBI supports this, but it would be good to be able to add arbitrary text annotations to the timeline to record certain events, and explain big changes - new runtime in use, some change to the benchmarking platform/setup, etc.

**Comment by DamianEdwards** [comment]
We have manual annotations at the bottom of the page now 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/249088/226051320-fee4a460-3c20-4c59-b918-c35b887e8c5e.png">
