### ISSUE TITLE
Performance regression: Plaintext, MvcPlaintext, Plaintext, ResponseCachingPlaintextRequestNoCache, ResponseCachingPlaintextResponseNoCache ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#639]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MemoryCachePlaintext | Linux, http, KestrelSockets | 2019-02-09 08:21:14Z | 3343024 | 3031860 | -9.31 % | -7.66 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-02__
Microsoft.NetCore.App __3.0.0-preview-27405-2__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-05__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/45ecfad074bf6abefd6d87b8bb18b94afaed4ede...32da2679f86ec0b19c6bcad25ed500ddf5ff845f

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MemoryCachePlaintext | Linux, http, KestrelSockets | 2019-02-09 12:24:53Z | 3213340 | 3083776 | -4.03 % | -3.19 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-05__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-07__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/32da2679f86ec0b19c6bcad25ed500ddf5ff845f...35b99e44cef7a4ca9bb2775bef36159532e32b21

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcPlaintext | Linux, http, KestrelSockets | 2019-02-09 16:08:26Z | 1519639 | 1418883 | -6.63 % | -3.23 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-07__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/73843cc9a5a2bfc9920c9233805add90d4636589...35b99e44cef7a4ca9bb2775bef36159532e32b21

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Plaintext | Linux, http, KestrelSockets | 2019-02-09 16:05:29Z | 3731076 | 3488819 | -6.49 % | -4.85 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-07__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/73843cc9a5a2bfc9920c9233805add90d4636589...35b99e44cef7a4ca9bb2775bef36159532e32b21

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Plaintext | Linux, https, KestrelSockets | 2019-02-09 16:19:05Z | 1988622 | 1908299 | -4.04 % | -3.75 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-07__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-09__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/35b99e44cef7a4ca9bb2775bef36159532e32b21...8f49bdf195efbcf3172eae8b3a8acbf862777b83

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| ResponseCachingPlaintextRequestNoCache | Linux, http, KestrelSockets | 2019-02-09 12:28:37Z | 726779 | 72166 | -90.07 % | -37.3 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-05__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-07__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/32da2679f86ec0b19c6bcad25ed500ddf5ff845f...35b99e44cef7a4ca9bb2775bef36159532e32b21

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| ResponseCachingPlaintextResponseNoCache | Linux, http, KestrelSockets | 2019-02-09 12:27:53Z | 1848896 | 75761 | -95.9 % | -65.31 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-05__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-07__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/32da2679f86ec0b19c6bcad25ed500ddf5ff845f...35b99e44cef7a4ca9bb2775bef36159532e32b21

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| StaticFiles | Linux, http, KestrelSockets | 2019-02-09 12:12:14Z | 3399602 | 3120037 | -8.22 % | -12.24 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview-19108-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19108-07__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/73843cc9a5a2bfc9920c9233805add90d4636589...35b99e44cef7a4ca9bb2775bef36159532e32b21

**Comment by davidfowl** [comment]
@jkotalik looks like some of this may be impacted by the pipe writer changes.
