### ISSUE TITLE
Scenarios are not running: DbMultiQueryDapper, DbMultiQueryEf, DbMultiQueryMongoDb, DbMultiQueryRaw, DbSingleQueryDapper ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#644]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| DbMultiQueryDapper | Windows, Cloud, http, KestrelSockets | 2/13/19 2:46:01 PM +00:00 |
| DbMultiQueryEf | Windows, Cloud, http, KestrelSockets | 2/13/19 2:47:37 PM +00:00 |
| DbMultiQueryMongoDb | Windows, Cloud, http, KestrelSockets | 2/13/19 2:46:48 PM +00:00 |
| DbMultiQueryRaw | Windows, Cloud, http, KestrelSockets | 2/13/19 2:45:12 PM +00:00 |
| DbSingleQueryDapper | Windows, Cloud, http, KestrelSockets | 2/13/19 2:40:13 PM +00:00 |
| DbSingleQueryEf | Windows, Cloud, http, KestrelSockets | 2/13/19 2:41:49 PM +00:00 |
| DbSingleQueryMongoDb | Windows, Cloud, http, KestrelSockets | 2/13/19 2:41:00 PM +00:00 |
| DbSingleQueryRaw | Windows, Cloud, http, KestrelSockets | 2/13/19 2:39:25 PM +00:00 |
| Json | Windows, Cloud, h2, KestrelSockets | 2/13/19 2:32:08 PM +00:00 |
| Json | Windows, Cloud, h2c, KestrelSockets | 2/13/19 2:32:56 PM +00:00 |
| MemoryCachePlaintext | Windows, Cloud, http, KestrelSockets | 2/13/19 2:33:44 PM +00:00 |
| MemoryCachePlaintextSetRemove | Windows, Cloud, http, KestrelSockets | 2/13/19 2:34:33 PM +00:00 |
| MvcDbMultiQueryDapper | Windows, Cloud, http, KestrelSockets | 2/13/19 2:49:15 PM +00:00 |
| MvcDbMultiQueryEf | Windows, Cloud, http, KestrelSockets | 2/13/19 2:50:05 PM +00:00 |
| MvcDbMultiQueryRaw | Windows, Cloud, http, KestrelSockets | 2/13/19 2:48:26 PM +00:00 |
| MvcDbSingleQueryDapper | Windows, Cloud, http, KestrelSockets | 2/13/19 2:43:32 PM +00:00 |
| MvcDbSingleQueryEf | Windows, Cloud, http, KestrelSockets | 2/13/19 2:44:23 PM +00:00 |
| MvcDbSingleQueryRaw | Windows, Cloud, http, KestrelSockets | 2/13/19 2:42:43 PM +00:00 |
| MvcPlaintext | Windows, Cloud, http, KestrelLibuv | 2/13/19 2:11:20 PM +00:00 |
| PlaintextNonPipelined | Windows, Cloud, http, KestrelSockets | 2/13/19 2:08:10 PM +00:00 |
| ResponseCachingPlaintextCached | Windows, Cloud, http, KestrelSockets | 2/13/19 2:35:20 PM +00:00 |
| ResponseCachingPlaintextCachedDelete | Windows, Cloud, http, KestrelSockets | 2/13/19 2:36:09 PM +00:00 |
| ResponseCachingPlaintextRequestNoCache | Windows, Cloud, http, KestrelSockets | 2/13/19 2:37:48 PM +00:00 |
| ResponseCachingPlaintextResponseNoCache | Windows, Cloud, http, KestrelSockets | 2/13/19 2:36:57 PM +00:00 |
| ResponseCachingPlaintextVaryByCached | Windows, Cloud, http, KestrelSockets | 2/13/19 2:38:36 PM +00:00 |

**Comment by sebastienros** [comment]
Fixed
