### ISSUE TITLE
Scenarios are not running: BasicViews.GetTagHelpers, ConnectionClose, ConnectionClose, ConnectionClose, ConnectionClose ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#645]
Some scenarios have stopped running:

| Scenario | Environment | Last Run |
| -------- | ----------- | -------- |
| BasicViews.GetTagHelpers | Windows, Cloud, http, KestrelSockets | 2/13/19 3:30:18 PM +00:00 |
| ConnectionClose | Windows, Cloud, http, KestrelSockets | 2/13/19 3:39:33 PM +00:00 |
| ConnectionClose | Windows, Cloud, https, KestrelSockets | 2/13/19 3:40:08 PM +00:00 |
| ConnectionClose | Windows, Cloud, http, KestrelLibuv | 2/13/19 3:40:46 PM +00:00 |
| ConnectionClose | Windows, Cloud, https, KestrelLibuv | 2/13/19 3:41:21 PM +00:00 |
| HttpClient | Windows, Cloud, http, KestrelSockets | 2/13/19 3:33:33 PM +00:00 |
| HttpClientFactory | Windows, Cloud, http, KestrelSockets | 2/13/19 3:35:17 PM +00:00 |
| HttpClientParallel | Windows, Cloud, http, KestrelSockets | 2/13/19 3:34:22 PM +00:00 |

**Comment by sebastienros** [comment]
Fixed
