### ISSUE TITLE
Bad responses: Json, Json

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#651]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Json | Windows, Cloud, http, IISInProcess | 2/16/19 3:23:54 AM +00:00 | 457959 |
| Json | Windows, Cloud, http, IISOutOfProcess | 2/16/19 3:24:46 AM +00:00 | 215982 |

**Comment by davidfowl** [comment]
Fixed
