### ISSUE TITLE
Bad responses: Jil, Json, Json, Json, Json ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#653]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Jil | Linux, Physical, http, KestrelSockets | 2/16/19 4:18:48 AM +00:00 | 336734 |
| Json | Linux, Physical, http, KestrelSockets | 2/16/19 4:17:20 AM +00:00 | 1057494 |
| Json | Linux, Physical, http, KestrelLibuv | 2/16/19 4:18:04 AM +00:00 | 981653 |
| Json | Linux, Physical, https, KestrelSockets | 2/16/19 4:24:57 AM +00:00 | 1028843 |
| Json | Linux, Physical, https, KestrelLibuv | 2/16/19 4:25:42 AM +00:00 | 960843 |
| Json | Linux, Physical, h2, KestrelSockets | 2/16/19 4:28:41 AM +00:00 | 2107436 |
| Json | Linux, Physical, h2c, KestrelSockets | 2/16/19 4:29:27 AM +00:00 | 2122522 |

**Comment by davidfowl** [comment]
Fixed
