### ISSUE TITLE
Bad responses: Jil, Json, Json, Json, Json ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#654]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Jil | Windows, Cloud, http, KestrelSockets | 2/16/19 6:29:51 AM +00:00 | 1247 |
| Json | Windows, Cloud, http, KestrelSockets | 2/16/19 6:27:39 AM +00:00 | 817211 |
| Json | Windows, Cloud, http, KestrelLibuv | 2/16/19 6:28:46 AM +00:00 | 702718 |
| Json | Windows, Cloud, https, KestrelSockets | 2/16/19 6:37:35 AM +00:00 | 615024 |
| Json | Windows, Cloud, https, KestrelLibuv | 2/16/19 6:38:40 AM +00:00 | 524114 |
| Json | Windows, Cloud, https, HttpSys | 2/16/19 6:39:45 AM +00:00 | 516986 |

**Comment by davidfowl** [comment]
Fixed
