### ISSUE TITLE
Performance regression: Json, Json, Json, Jil, Json

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#656]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Jil | Linux, http, KestrelSockets | 2019-02-16 12:16:09Z | 772564 | 17244 | -97.77 % | -66.12 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/6bafb7cb6f06a5d5795047d39146df22d24deb50...394ef0ab93f8f53591b74154db4445b6f179277b

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, http, KestrelSockets | 2019-02-16 12:14:41Z | 745321 | 17222 | -97.69 % | -73.3 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/6bafb7cb6f06a5d5795047d39146df22d24deb50...394ef0ab93f8f53591b74154db4445b6f179277b

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, https, KestrelLibuv | 2019-02-16 12:21:21Z | 531990 | 2944 | -99.45 % | -59.87 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/6bafb7cb6f06a5d5795047d39146df22d24deb50...394ef0ab93f8f53591b74154db4445b6f179277b

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, h2, KestrelSockets | 2019-02-16 12:24:20Z | 278452 | 0 | -100 % | -41.33 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/6bafb7cb6f06a5d5795047d39146df22d24deb50...394ef0ab93f8f53591b74154db4445b6f179277b

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, h2c, KestrelSockets | 2019-02-16 12:25:02Z | 589624 | 0 | -100 % | -77.75 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-04__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/6bafb7cb6f06a5d5795047d39146df22d24deb50...394ef0ab93f8f53591b74154db4445b6f179277b

**Comment by davidfowl** [comment]
Fixed
