### ISSUE TITLE
Performance regression: Json, Json, Json, Json, Json ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#657]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, http, KestrelSockets | 2019-02-16 16:15:43Z | 70162 | 17249 | -75.42 % | -5.38 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-10__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/394ef0ab93f8f53591b74154db4445b6f179277b...63a8b14619ec0cf9570725d3b53844fb9806ea88

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, http, KestrelLibuv | 2019-02-16 16:16:27Z | 65190 | 25220 | -61.31 % | -3.48 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-10__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/394ef0ab93f8f53591b74154db4445b6f179277b...63a8b14619ec0cf9570725d3b53844fb9806ea88

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, https, KestrelSockets | 2019-02-16 16:21:39Z | 68136 | 2945 | -95.68 % | -9.18 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-10__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/394ef0ab93f8f53591b74154db4445b6f179277b...63a8b14619ec0cf9570725d3b53844fb9806ea88

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, https, KestrelLibuv | 2019-02-16 16:22:23Z | 63826 | 2949 | -95.38 % | -6.92 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-10__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/394ef0ab93f8f53591b74154db4445b6f179277b...63a8b14619ec0cf9570725d3b53844fb9806ea88

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, h2, KestrelSockets | 2019-02-16 16:25:18Z | 70248 | 0 | -100 % | -10.32 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-10__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/394ef0ab93f8f53591b74154db4445b6f179277b...63a8b14619ec0cf9570725d3b53844fb9806ea88

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| Json | Linux, h2c, KestrelSockets | 2019-02-16 16:26:00Z | 70751 | 0 | -100 % | -9.33 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-08__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview3-19115-10__
Microsoft.NetCore.App __3.0.0-preview-27408-1__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/394ef0ab93f8f53591b74154db4445b6f179277b...63a8b14619ec0cf9570725d3b53844fb9806ea88

**Comment by davidfowl** [comment]
Fixed
