### ISSUE TITLE
Bad responses: Jil, Jil, Json, Json, Json ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#659]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Jil | Linux, Physical, http, KestrelSockets | 2/17/19 12:16:20 AM +00:00 | 336734 |
| Jil | Windows, Cloud, http, KestrelSockets | 2/17/19 2:27:27 AM +00:00 | 98950 |
| Json | Windows, Cloud, http, IISInProcess | 2/16/19 11:14:42 PM +00:00 | 492094 |
| Json | Windows, Cloud, http, IISOutOfProcess | 2/16/19 11:15:36 PM +00:00 | 227872 |
| Json | Linux, Physical, http, KestrelSockets | 2/17/19 12:14:51 AM +00:00 | 1057494 |
| Json | Linux, Physical, http, KestrelLibuv | 2/17/19 12:15:35 AM +00:00 | 981653 |
| Json | Linux, Physical, https, KestrelSockets | 2/17/19 12:20:48 AM +00:00 | 1028843 |
| Json | Linux, Physical, https, KestrelLibuv | 2/17/19 12:21:32 AM +00:00 | 960843 |
| Json | Linux, Physical, h2, KestrelSockets | 2/17/19 12:24:29 AM +00:00 | 2107436 |
| Json | Linux, Physical, h2c, KestrelSockets | 2/17/19 12:25:12 AM +00:00 | 2122522 |
| Json | Windows, Cloud, http, KestrelSockets | 2/17/19 2:25:08 AM +00:00 | 817211 |
| Json | Windows, Cloud, http, KestrelLibuv | 2/17/19 2:26:18 AM +00:00 | 702718 |
| Json | Windows, Cloud, https, KestrelSockets | 2/17/19 2:35:22 AM +00:00 | 615024 |
| Json | Windows, Cloud, https, KestrelLibuv | 2/17/19 2:36:27 AM +00:00 | 524114 |
| Json | Windows, Cloud, https, HttpSys | 2/17/19 2:37:17 AM +00:00 | 516986 |

**Comment by sebastienros** [comment]
They might have been run a few hours before you closed the previous one, as they are only run every 4 hours. Closing and if it reopens then there will be an issue.
