### ISSUE TITLE
Bad responses: DbMultiUpdateDapper, DbMultiUpdateEf, DbMultiUpdateRaw, Jil, Jil ...

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#661]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| DbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 2/17/19 4:43:39 PM +00:00 | 117 |
| DbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 2/17/19 4:44:26 PM +00:00 | 71 |
| DbMultiUpdateRaw | Linux, Cloud, http, KestrelSockets | 2/17/19 4:42:53 PM +00:00 | 166 |
| Jil | Linux, Physical, http, KestrelSockets | 2/17/19 4:16:19 PM +00:00 | 336734 |
| Jil | Linux, Cloud, http, KestrelSockets | 2/17/19 4:16:41 PM +00:00 | 98593 |
| Jil | Windows, Cloud, http, KestrelSockets | 2/17/19 6:27:42 PM +00:00 | 98950 |
| Json | Linux, Physical, http, KestrelSockets | 2/17/19 4:14:50 PM +00:00 | 1057494 |
| Json | Linux, Cloud, http, KestrelSockets | 2/17/19 4:15:10 PM +00:00 | 525186 |
| Json | Linux, Physical, http, KestrelLibuv | 2/17/19 4:15:35 PM +00:00 | 981653 |
| Json | Linux, Cloud, http, KestrelLibuv | 2/17/19 4:15:56 PM +00:00 | 443222 |
| Json | Linux, Physical, https, KestrelSockets | 2/17/19 4:20:51 PM +00:00 | 1028843 |
| Json | Linux, Cloud, https, KestrelSockets | 2/17/19 4:21:14 PM +00:00 | 412441 |
| Json | Linux, Physical, https, KestrelLibuv | 2/17/19 4:21:35 PM +00:00 | 960843 |
| Json | Linux, Cloud, https, KestrelLibuv | 2/17/19 4:21:59 PM +00:00 | 344227 |
| Json | Linux, Physical, h2, KestrelSockets | 2/17/19 4:24:32 PM +00:00 | 2107436 |
| Json | Linux, Cloud, h2, KestrelSockets | 2/17/19 4:25:02 PM +00:00 | 914888 |
| Json | Linux, Physical, h2c, KestrelSockets | 2/17/19 4:25:13 PM +00:00 | 2122522 |
| Json | Linux, Cloud, h2c, KestrelSockets | 2/17/19 4:25:48 PM +00:00 | 1188830 |
| Json | Windows, Cloud, http, KestrelSockets | 2/17/19 6:25:31 PM +00:00 | 817211 |
| Json | Windows, Cloud, http, KestrelLibuv | 2/17/19 6:26:36 PM +00:00 | 702718 |
| Json | Windows, Cloud, https, KestrelSockets | 2/17/19 6:35:35 PM +00:00 | 615024 |
| Json | Windows, Cloud, https, KestrelLibuv | 2/17/19 6:36:39 PM +00:00 | 524114 |
| Json | Windows, Cloud, https, HttpSys | 2/17/19 6:37:45 PM +00:00 | 516986 |
| Json | Windows, Cloud, http, IISInProcess | 2/17/19 7:17:07 PM +00:00 | 492094 |
| Json | Windows, Cloud, http, IISOutOfProcess | 2/17/19 7:17:59 PM +00:00 | 227872 |
| MemoryCachePlaintext | Linux, Cloud, http, KestrelSockets | 2/17/19 4:26:32 PM +00:00 | 58 |
| MemoryCachePlaintextSetRemove | Linux, Cloud, http, KestrelSockets | 2/17/19 4:27:17 PM +00:00 | 62 |
| MvcDbFortunesEf | Linux, Cloud, http, KestrelSockets | 2/17/19 4:52:01 PM +00:00 | 1 |
| MvcDbMultiQueryEf | Linux, Cloud, http, KestrelSockets | 2/17/19 4:42:06 PM +00:00 | 1 |
| MvcDbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 2/17/19 4:45:57 PM +00:00 | 50 |
| MvcDbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 2/17/19 4:46:42 PM +00:00 | 5 |
| MvcPlaintext | Linux, Cloud, http, KestrelSockets | 2/17/19 4:08:46 PM +00:00 | 52 |
| MvcPlaintext | Linux, Cloud, http, KestrelLibuv | 2/17/19 4:09:32 PM +00:00 | 46 |
| Plaintext | Linux, Cloud, http, KestrelLibuv | 2/17/19 4:03:24 PM +00:00 | 47 |
| Plaintext | Linux, Cloud, http, KestrelSockets | 2/17/19 4:05:45 PM +00:00 | 45 |
| PlaintextNonPipelined | Windows, Cloud, https, KestrelSockets | 2/17/19 6:38:49 PM +00:00 | 1 |
| PlaintextPlatform | Linux, Cloud, http, KestrelSockets | 2/17/19 4:02:31 PM +00:00 | 50 |
| ResponseCachingPlaintextCached | Linux, Cloud, http, KestrelSockets | 2/17/19 4:28:03 PM +00:00 | 56 |
| ResponseCachingPlaintextRequestNoCache | Linux, Cloud, http, KestrelSockets | 2/17/19 4:30:19 PM +00:00 | 58 |
| ResponseCachingPlaintextResponseNoCache | Linux, Cloud, http, KestrelSockets | 2/17/19 4:29:34 PM +00:00 | 61 |
| ResponseCachingPlaintextVaryByCached | Linux, Cloud, http, KestrelSockets | 2/17/19 4:31:04 PM +00:00 | 63 |
| StaticFiles | Linux, Cloud, http, KestrelSockets | 2/17/19 4:12:35 PM +00:00 | 39 |

**Comment by davidfowl** [comment]
@sebastienros as part of this issue it would be great if the version of AspNetCore, .net core and the benchmarks repo that were used
