### ISSUE TITLE
Bad responses: BasicViews.GetTagHelpers, HttpClientParallel, Json, Json, ResponseCachingPlaintextCachedDelete

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#662]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| BasicViews.GetTagHelpers | Windows, Cloud, http, KestrelSockets | 2/19/19 10:37:09 PM +00:00 | 24 |
| HttpClientParallel | Windows, Cloud, http, KestrelSockets | 2/19/19 10:41:09 PM +00:00 | 5 |
| Json | Windows, Cloud, h2, KestrelSockets | 2/19/19 6:41:03 PM +00:00 | 1767064 |
| Json | Windows, Cloud, h2c, KestrelSockets | 2/19/19 6:42:19 PM +00:00 | 2284314 |
| ResponseCachingPlaintextCachedDelete | Windows, Cloud, http, KestrelSockets | 2/19/19 6:46:38 PM +00:00 | 9958738 |

**Comment by davidfowl** [comment]
Bad run?
