### ISSUE TITLE
Is node only benchmarked with single threading? Or are clusters being used?

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/Benchmarks#67]

**Comment by offero** [comment]
Why was this closed? I have the same question.

**Comment by MarkPieszak** [comment]
Reopened sorry about that!

**Comment by davidfowl** [comment]
No need to ask here, look at the techempower benchmarks https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=plaintext. https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/app.js#L2

**Comment by davidfowl** [comment]
@DamianEdwards @mikeharder We should just clear the readme because those results are super old...

**Comment by offero** [comment]
@davidfowl Great, thanks for the links.

**Comment by MarkPieszak** [comment]
Thank you David! @davidfowl
