### ISSUE TITLE
Benchmarks for ASP.NET 5

### ISSUE THREAD

**Issue by JamesNK** [aspnet/benchmarks#68]
The repo description needs to be updated:

Benchmarks for ASP.NET 5 -> Benchmarks for ASP.NET Core

**Comment by Lewiscowles1986** [comment]
Whilst updating it would be interesting to see when benchmarks are run, they are run on Windows and Linux distro's to the same source, maybe sharing the configs, as it looks like Windows x64 has gone to > 1,000,000 req/s and none of those tests were repeated on Linux
