### ISSUE TITLE
why don't you add these in the official techempower repo?

### ISSUE THREAD

**Issue by boussou** [aspnet/benchmarks#86]
I am interested in returning back & learning asp.net.
I would like to see how it compares to java & js, at least for the single query & update tests

**Comment by boussou** [comment]
it seems there's one - it just that they did not complete in round 12

**Comment by benaadams** [comment]
ASP.NET Core is not currently included/submitted to the benchmarks; as I understand it it will be when released

**Comment by boussou** [comment]
Great
