### ISSUE TITLE
Add benchmark with warning-level logging enabled

### ISSUE THREAD

**Issue by halter73** [aspnet/Benchmarks#889]
https://github.com/aspnet/AspNetCore/issues/6924

**Comment by sebastienros** [comment]
We already measured it, and for Console at that time it was 20%. An issue is already filed I think. But that a good idea to have a custom benchmark that is tracked for it.

**Comment by halter73** [comment]
> But that a good idea to have a custom benchmark that is tracked for it.

Agreed. I opened this in part because logging is an area particularly at risk for regressions considering it's possible to write logs in less-than-optimal ways.

**Comment by benaadams** [comment]
Maybe warning level? I assume warning logs should be something you should take action on; so would probably want to output at a min level in production?

**Comment by anurse** [comment]
What's the outcome here @sebastienros ? Do we have this benchmark scenario now?

**Comment by sebastienros** [comment]
Don't know why it's closed

**Comment by anurse** [comment]
:eyes: 😛

**Comment by benaadams** [comment]
Perhaps with the default builder and logging level set via config?

**Comment by sebastienros** [comment]
Ah yes, that must be it. I just did it.
