### ISSUE TITLE
Performance regression: MvcJson, MvcJson

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Benchmarks#933]
A performance regression has been detected for the following scenarios:

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcJson | Windows, http, KestrelSockets | 2019-04-18 22:21:20Z | 469726 | 460431 | -1.98 % | -15.95 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview5-19216-08__
Microsoft.NetCore.App __3.0.0-preview5-27613-11__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview5-19216-09__
Microsoft.NetCore.App __3.0.0-preview5-27613-11__

Commits:

__Microsoft.AspNetCore.App__
https://github.com/aspnet/AspNetCore/compare/2dc5694ecd1bd95e9091f6942657ebe1da6e0bb7...004ac259837b2c0ea63c49a49f2cbd9a6c0c9d97

| Scenario | Environment | Date | Old RPS | New RPS | Change | Deviation |
| -------- | ----------- | ---- | ------- | ------- | ------ | --------- |
| MvcJson | Windows, http, KestrelSockets | 2019-04-19 04:48:24Z | 467776 | 461621 | -1.32 % | -10.56 σ |

Before versions:
Microsoft.AspNetCore.App __3.0.0-preview5-19216-09__
Microsoft.NetCore.App __3.0.0-preview5-27613-11__

After versions:
Microsoft.AspNetCore.App __3.0.0-preview5-19216-09__
Microsoft.NetCore.App __3.0.0-preview5-27614-10__

Commits:

__Microsoft.NetCore.App / Core FX__
https://github.com/dotnet/corefx/compare/00e9390eb0e9b95a410bd3e91b2c58cf9ec85d95...81e0e2cb79e272e6e270c6562017b64f9c773e99

__Microsoft.NetCore.App / Core CLR__
https://github.com/dotnet/coreclr/compare/f08c5c39c5bd7f594ff0b42a7167e6be9205ede7...6c9438d58613267701396c7a25eae4c3a5e2c570

**Comment by sebastienros** [comment]
False positive
