### ISSUE TITLE
Update readme (publish results)

### ISSUE THREAD

**Issue by aL3891** [aspnet/Benchmarks#96]
@davidfowl mentioned on slack that there are now automated runs that publish results at least for the plain text benchmarks, but that these are only published internally. Please consider making the results available externally or at least updating the readme. It seems there's been some pretty significant progress :) 

Also, is the techempower hardware the same as smurflab or is that another setup? 

cc @DamianEdwards

**Comment by simonmurdock** [comment]
Don't forget the hardware for 1mil isbt the same as 5 mil

**Comment by mikeharder** [comment]
I updated `README.md` with the current results for plaintext with pipelining (1,174,881).  We are looking into ways we can share our internal benchmark results in real-time with the community.
