### ISSUE TITLE
Question:Pipelining for Techempower workload results

### ISSUE THREAD

**Issue by vkvenkat** [aspnet/benchmarks#97]
I have been analyzing the Techempower benchmark results with dotnet core (https://github.com/aspnet/benchmarks/blob/master/results/Results.xlsx). Wanted to check if pipelining was enabled for the mentioned scenarios (Plaintext, Json in particular). If so, what was the pipelining depth used? Also, I believe the number of wrk threads was set to the number of cores in the server. Would be great if I could also get the thread counts.

**Comment by benaadams** [comment]
Check the Load Parameters column on the readme page https://github.com/aspnet/benchmarks

**Comment by mikeharder** [comment]
Both benchmarks use 32 wrk threads.  Plaintext uses pipeline depth of 16, while Json does not use pipelining.
